Subtask 1
Tauders/denis-tasks pull request #20
Opened 2021-09-02 13:59 UTC by St1ke

2021-11-13 10:30 UTC, CodingFeles requested changes
В целом, хорошо. 
Хотелось бы уйти от выявления некорректного вводе, через отлов исключений, в тех случаях где это можно проверить другими способами.

2021-11-13 10:30 UTC, CodingFeles commented on Subtasks/Subtask-1/Subtask-1/Program.cs
> +            int N;
Тут ошибки нет, но хочу сделать ремарку на будущее: стоит всегда явно инициализировать значения переменных. В шарпе с этим получше, но все равно очень частая ошибка - забыть задать начальное значение, пропустить, что есть ветки исполнения, где ей не задаются значения и смотреть на странное поведение програмы.

2021-11-13 10:30 UTC, CodingFeles commented on Subtasks/Subtask-1/Subtask-1/Program.cs
> +                try
Было бы здорово переписать цикл и убрать проверки через исключения. Ты ниже используешь метод, который поможет тебе "попытаться" сконвертировать строку в инт.

2021-11-13 10:30 UTC, CodingFeles commented on Subtasks/Subtask-1/Subtask-1/Program.cs
> +            string[] cosmo = new string[N];
cosmo? Я не очень понимаю, что подразумевает это название. Может я просто не понял. Но, возможно, стоит выбрать название получше.

2021-11-13 10:30 UTC, CodingFeles commented on Subtasks/Subtask-1/Subtask-1/Program.cs
> +                    try
Исключения - не самый "дешёвый" способ работы. Лучше их оставлять для "исключительных" ситуаций.
Ситуация, когда пользователь ввёл некорректный индекс - вполне рядовая, хоть это и ошибка. Подумай как ты можешь проверить индекс массива сам и сообщить об ошибки пользователю без генерации исключения.

2021-11-13 10:30 UTC, CodingFeles commented on Subtasks/Subtask-1/Subtask-1/Program.cs
> +                    Console.WriteLine("Вы ввели неверный номер элемента массива");
Наверное, "неверный номер" - это скорее к первой ошибке, когда номер не работает как индекс массива. Тут же пользователь в целом, ввёл не номер, а какой-то набор символов не поддающийся переводу в инт.

2021-11-15 16:49 UTC, Tauders requested changes
Помести в отдельную папку, так как теперь не ты один делаешь эти задачи, путь должен быть примерно таким:

`Subtasks/Evgeniy/Subtask-1/...`

2021-11-15 17:10 UTC, Tauders approved these changes, later dismissed

2021-12-02 16:13 UTC, Tauders requested changes

2021-12-02 16:13 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-1/Subtask-1/Program.cs
> +            string g = Console.ReadLine();
Пожалуйста, используй более осмысленные имена.

2021-12-02 16:13 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-1/Subtask-1/Program.cs
> +            }
Пожалуйста, переделай без `while (true)` - просто ради практики. Если не понимаешь, как - можем обсудить.

2021-12-02 16:13 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-1/Subtask-1/Program.cs
> +                    Console.WriteLine("Ошибка, введите число");
Можешь уточнить, что число положительное.

2021-12-02 16:13 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-1/Subtask-1/Program.cs
> +                bool result = int.TryParse(s, out a);
`int a;` пожалуйста, более осмысленные имена.

2021-12-02 16:13 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-1/Subtask-1/Program.cs
> +            string s = Console.ReadLine();
Пожалуйста, более осмысленные имена.

2021-12-02 16:13 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-1/Subtask-1/Program.cs
> +                }
А если число отрицательное?

2021-12-03 10:38 UTC, St1ke commented on Subtasks/Evgeniy/Subtask-1/Subtask-1/Program.cs
> +                }
38 строка проверяет и этот случай для правильного ввода. 42 строка указывает на ошибку неверного ввода, а 46 строка ловит все остальные ошибки, ввод сиволов, отрицательных чисел, или букв

2021-12-03 10:39 UTC, St1ke commented on Subtasks/Evgeniy/Subtask-1/Subtask-1/Program.cs
> +                }
Проверил ещё раз и всё в норме, ошибок не увидел

2021-12-03 10:52 UTC, St1ke commented on Subtasks/Evgeniy/Subtask-1/Subtask-1/Program.cs
> +            }
А это как понять? можно точнее формулировать? другой вариант цикла использовать? Если нет, то не понимаю

2021-12-03 11:01 UTC, CodingFeles commented on Subtasks/Evgeniy/Subtask-1/Subtask-1/Program.cs
> +            }
Условие выхода использовать другое. По сути, while(true) - крутись без конца, а я закончу сам как-нибудь. Такое имеет место быть, но в небольшом количестве случаев. 
Здесь предлагается переделать условие цикла, чтобы действия были теми же самыми, но не было while(true).

Ожидается while(какое-то условие).
Условие у тебя уже есть - ты, когда оно исполняется, вызываешь break - то есть выход из цикла. Тут вопрос больше реорганизации.

Обсуди с Вовой поподробнее.

2021-12-03 11:08 UTC, St1ke commented on Subtasks/Evgeniy/Subtask-1/Subtask-1/Program.cs
> +            }
> Да уже, пока занимаюсь моим любимым занятием - правильным наименованием переменных

2021-12-04 10:15 UTC, Tauders approved these changes

2021-12-05 15:01 UTC, CodingFeles approved these changes

2021-12-05 15:01 UTC, merged