[SubtasksJs-1] Добавила решение задачи 1
Tauders/denis-tasks pull request #26
Opened 2021-11-28 10:33 UTC by VeronikaFront

2021-11-28 13:06 UTC, Tauders requested changes

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/index.html
> +        <div class="form">
Здесь лучше использовать тег `<form>` так как это имеет семантический и практический смысл. Практический смысл в том, что `form` имеет событие `submit`.

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/index.html
> +        <h1 class="forma_heading">
Почему `forma_heading`?

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/index.html
> +                <input class="forma_data" id="forData" type="text" name="data" placeholder="что-то на тюленьем" onkeyup="start()">
Почему имя `forData` и `forma_data`? Зачем `name`?

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/index.html
> +            <button class="forma_btn" type="submit" id="submitData">
Почему имя `forma_btn`? Зачем `submitData`?

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/index.html
> +                    <svg width="190px" height="80px" viewBox="0 0 190 80" class="border">
Зачем `width="190px" height="80px"`?

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/index.html
> +                    <svg width="190px" height="80px" viewBox="0 0 190 80" class="border">
Зачем эта `svg` нужен?

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    background-image: url('./images/background-2.png');
Почему бы не использовать одну и ту же картинку и развернуть её?

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +@import url('https://fonts.googleapis.com/css?family=Lato:100&display=swap');
Все ли параметры нужны? Я проверил, не все, удали лишнее.

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +h1.forma_heading {
А зачем здесь `h1`?

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    color: #666;
Цвет шрифта не очень хорошо виден, можно проверить на https://webaim.org/resources/contrastchecker/ там результат такой:
![image](https://user-images.githubusercontent.com/4114636/143765518-17faa47b-2e7f-4fac-ae25-78b065684a41.png)
Много `Fail` не очень хорошо.

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    height: 80px;
Попробуй убери эти параметры, может быть лучше в плане разных браузеров.

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +button.forma_btn {
А надо ли уточнять, что здесь `button`?

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +svg {
А почему тег `svg`, а не какой-то более конкретный класс?

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +.forma_btn:hover svg {
Опять же - почему `svg`, а не класс?

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +@media screen and (max-width:1280px) {
Круто, что позаботилась о мобильном лейауте?

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.js
> +function start(e) {
Название функции не говорящее - что значит `start`? Код читают значительно чаще, чем пишут, так что надо стараться делать говорящие имена.

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/index.html
> +                <input class="forma_data" id="forData" type="text" name="data" placeholder="что-то на тюленьем" onkeyup="start()">
Прицеплять так события:
```
onkeyup="start()"
``` 
не очень хорошая практика.

В рамках задачи это не ошибка, но лучше так не делать.

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.js
> +function dataBtn() {
Название функции не очень - что значит `dataBtn`?

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.js
> +    if (e.keyCode === 13) { document.getElementById('submitData').click() }
Практика "магических чисел" не очень хорошая. Здесь это очевидно фронт-енд разработчикам, но лучше выносить в константу, например.

```
const ENTER_KEY_CODE = 13;
```
и потом 
```
     if (e.keyCode === ENTER_KEY_CODE ) { document.getElementById('submitData').click() }
```

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.js
> +    if (e.keyCode === 13) { document.getElementById('submitData').click() }
Не самый очевидный вызов функции 
```
document.getElementById('submitData').click() 
```

Может всё же так не делать, а напрямую вызывать функцию?

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.js
> +document.querySelector('.forma_btn').addEventListener('click', dataBtn);
Стоит использовать другой селектор и другое событие для этого использовать.

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.js
> +    let nerpa = document.querySelector('.forma_data').value;
Молодец, что используешь `let`, но название переменной не очень хорошее - непонятно, что это должно значить.

2021-11-28 13:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.js
> +    document.getElementById('forData').value = '';
Ты получаешь одно и тоже поле двумя разными способами:

```
document.querySelector('.forma_data')
```
и
```
document.getElementById('forData')
```
может не стоит так делать?

2021-11-30 14:07 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-1/index.html
> +        <h1 class="forma_heading">
Заголовок - `heading `
Заголовок в форме , поэтому `forma`

2022-04-11 14:54 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-1/index.html
> +                    <svg width="190px" height="80px" viewBox="0 0 190 80" class="border">
Он делает эффект

2022-04-11 14:56 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    color: #666;
Сделала #999, везде Pass

2022-04-11 15:45 UTC, Tauders requested changes
Удали лишнюю картинку

2022-04-11 15:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    max-width: 1920px;
Зачем этот параметр?

2022-04-11 15:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    max-width: 1920px;
Нужны ли эти параметры?

2022-04-11 15:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    position: relative;
Зачем параметр?

2022-04-11 15:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    height: 890px;
Почему именно такая высота?

2022-04-11 15:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +            align-items: center;
Пока не нужны параметры вида `-webkit` или `-ms`, в общем с префиксами. Они нужны только для супер продакшена.

2022-04-11 15:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    font-family: cursive;
Нужно?

2022-04-11 15:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    transform: rotateY(180deg);background-size: 500px;
Лучше на разных строках - будет читабельнее

2022-04-11 15:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    max-width: 1920px;
Нужно ли это?

2022-04-11 15:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    height: 890px;
Почему именно такая высота?

2022-04-11 15:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    right: 0;
Нужно ли это сейчас?

2022-04-11 15:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    text-align: center;
Нужно ли это?

2022-04-11 15:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +            flex-direction: column;
Удали, пожалуйста, с префиксами

2022-04-11 15:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +            justify-content: center;
Нужно?

2022-04-11 15:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    text-align: center;
Нужно?

2022-04-11 15:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    -o-transition: .3s;
Удали, пожалуйста, префиксы

2022-04-11 15:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    cursor: pointer;
Почему такой курсор?

2022-04-11 15:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    text-align: center;
Зачем?

2022-04-11 15:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    -o-transition: 1s ease-in-out;
Зачем префиксы?

2022-04-12 17:42 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    max-width: 1920px;
1. Устанавливает цвет фона, да, нужен;
2. Прямой необходимости нет;
3. Прямой необходимости нет;
4.Ограничивает ширину для больших экранов, чтобы выглядело приемлемо,  в данном случае, возможно, можно опустить.

2022-04-12 17:47 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    max-width: 1920px;
1. Margin: auto помогает избавиться от стандартных отступов, чтобы не было обреза у фоновых картинок.
2. Добавляет картинку - фон;
3. Чтобы она не дублировалась;
4. Делала тюленей нужного размера, убрала.
5. Максимальная ширина для контейнера для больших экранов, чтобы было читабельно, так скажем, убрала.

2022-04-12 17:47 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    height: 890px;
Чтобы тюлени не обрезались, сделала по-другому.

2022-04-12 17:49 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    position: relative;
1.Устанавливает позиционирование картинки-фона;
2. Так выглядело симпатичнее, без этого слишком ярко;
3. В данном случае прямой необходимости нет, убрала.

2022-04-12 17:51 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +            align-items: center;
На своей работе мы все делаем кроссбраузерно, надо чтобы везде максимально поддерживалось.
Убрала пока что, но я считаю, что они нужны.

2022-04-12 17:51 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    font-family: cursive;
Вообще-то делало заголовок на мой взгляд приятнее, убрала.

2022-04-12 17:51 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    transform: rotateY(180deg);background-size: 500px;
Случайность. Поправила.

2022-04-12 17:53 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    max-width: 1920px;
Абсолютная позиция нужна для отображения. 
Позиционирование фона смещает туда, куда мне надо.
Максимальную ширину убрала.

2022-04-12 17:53 UTC, seal-developer commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    right: 0;
Ширина нужна для отображения.
Прибивать вправо нет.

2022-04-12 17:54 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    height: 890px;
та же причина, что и с высотой у контейнера. Переделала по-другому.

2022-04-12 17:55 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    text-align: center;
1.Чтобы не дублировалась картинка;
2. Чтобы не перекрывала форму;
3. Это не надо.

2022-04-12 17:56 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +            justify-content: center;
Верхний отступ нет.
Флексы нужны для размещения.

2022-04-12 17:56 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +            flex-direction: column;
Удалила(

2022-04-12 17:57 UTC, seal-developer commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    text-align: center;
Да, текст по правому краю выбивается из общей картины всего по центру.

2022-04-12 17:57 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    -o-transition: .3s;
+

2022-04-12 17:57 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    cursor: pointer;
Изменила.

2022-04-12 17:59 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +    text-align: center;
Позиция нужна для правильного отображения эффекта.
По центру не надо.

2022-04-13 17:36 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-1/main.css
> +            align-items: center;
Вообще обычное такое добавляется автоматически всякими библиотеками, так что переписывать вручную такое обычно не надо.

2022-04-13 17:36 UTC, Tauders approved these changes

2022-04-13 17:39 UTC, merged