Subtask 2
Tauders/denis-tasks pull request #29
Opened 2022-01-23 19:15 UTC by St1ke

2022-01-23 19:27 UTC, Tauders requested changes

2022-01-23 19:27 UTC, Tauders commented on Subtasks/README.md
> +
Не меняй README.md, пожалуйста

2022-01-23 19:27 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            }
Вынеси в отдельный метод.

2022-01-23 19:27 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            int value = rnd.Next(3, 7);
Не очень хорошее название - слишком абсрактное

2022-01-23 19:27 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            string s = Console.ReadLine();
Не очень хорошее имя переменной - не говорящее.

2022-01-23 19:27 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            string[] numbers = new string[value];
Зачем его заводить здесь? Перемести его объявление вниз.

2022-01-23 19:27 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            int i = 0;
Не очень хорошее название.

2022-01-23 19:27 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +                if (firstSuccess)
Сделай чуть иначе, разницы нет, но код будет меньше.

```cs
if (int.TryParse(numbers[i], out int newNumbers))
{
```

Или же поменяй имя переменной.

2022-01-23 19:27 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +                    numbers = s.Split(new char[] { ' ' });
Код дублируется 3 раза, вынеси в отдельный метод.

2022-01-23 19:27 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +                    if (inputNumbers != "X")
Форматирование.

2022-01-23 19:27 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            while (inputNumbers != "X")
Код дублируется, перепиши.

2022-01-23 19:27 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +                         if (secondSuccess && newInputNumbers < value && newInputNumbers >= 0)
Или упрости, как выше, или поменяй название переменной.

2022-01-23 19:27 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +                Console.WriteLine("Выход из программы");
Распиши, почему.

2022-01-23 19:27 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            string actions = Console.ReadLine();
`actions` почему в множественном числе?

2022-01-25 10:31 UTC, St1ke commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            int value = rnd.Next(3, 7);
![image](https://user-images.githubusercontent.com/83986957/150960291-eee0df29-f25f-4ab9-8e2d-a9d6bb24c749.png)
пофиксил

2022-01-25 10:34 UTC, St1ke commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            string s = Console.ReadLine();
про какую именно переменную речь? очень тяжело понять тк тут их целых три

2022-01-25 10:35 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            string s = Console.ReadLine();
`s`

2022-01-25 10:37 UTC, St1ke commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            string s = Console.ReadLine();
![image](https://user-images.githubusercontent.com/83986957/150961206-b04b78ae-7cae-43fe-b1fb-52a211016e2e.png)
переименовал

2022-01-25 10:39 UTC, St1ke commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            string[] numbers = new string[value];
Это не сложно, но зачем?  чтоб визуально понимать где вводится массив и используется?

2022-01-25 10:41 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            string[] numbers = new string[value];
В том числе, да. Потом, если бы код разростался, то между объявлением и фактическим использованием могло бы быть всё больше места, становилось бы всё непонятнее и т.д. 
Неплохая практика объявлять и использовать переменные как можно ближе к месту фактического использования. Из этого есть исключения, но пока можешь придерживаться такого подхода.

2022-01-25 10:43 UTC, St1ke commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            string[] numbers = new string[value];
![image](https://user-images.githubusercontent.com/83986957/150962101-e208959d-05f4-43b7-bdd9-118cdd653342.png)
Исправлено

2022-01-25 10:45 UTC, CodingFeles commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            string[] numbers = new string[value];
Ты создаёшь массив. ``` new string[value] ``` - выполняет реальную работу по выделению памяти. Ты потом нигде это не используешь и просто перезаписываешь содержимое массива. Вопрос: зачем тогда создавать его тут?
Если хочется, можешь оставить объявление, без инициализации. Но проще перенести это двумя строчками ниже.

2022-01-25 10:46 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            string[] numbers = new string[value];
Коммент был про `numbers` массив.

2022-01-25 11:08 UTC, St1ke commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +                if (firstSuccess)
Не очень понимаю что "не так", звучит в духе, сделай что-нибудь, допустим имя переменной. "Первая проверка" вроде же норм?

2022-01-25 11:12 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +                if (firstSuccess)
"Первая проверка" не очень звучит, так как второй рядом нет? Первая для чего? И перевод то не такой: "Первый успех" звучит для названия переменной тоже странно - а где второй и т.д.

`isParsingSuccessful` или `isNumberParsed` или `isNumberParsedSuccessful` звучат лучше и понятнее.

Я же привёл способ, когда переменная отдельная вообще не нужна. Так ничего не поменяется, но код будет чуть меньше и не будет вопросов "если здесь есть переменная, то значит она для чего-то ещё нужна или какой в ней смысл".

2022-01-25 12:26 UTC, Tauders requested changes

2022-01-25 12:26 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            string action = Console.ReadLine();
Что, если пользователь введёт не разрешённые действия?

2022-01-27 16:10 UTC, Tauders requested changes

2022-01-27 16:10 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +                    total = Multiplication(choosenNumbers, counter);
Зачем во всех этих функциях `counter`? Потом он не используется в текущей функции и не понятно, зачем он там нужен.

2022-01-27 16:10 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            Console.WriteLine(total);
Это будет выводиться даже после того, как пользователь ввёл неверное действие?

2022-01-27 16:10 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +                    Console.WriteLine("Вы ввели неверный оператор действия. Попробуйте ещё раз");
Добавь для тренировки возможно заново ввести действие.

2022-01-27 16:10 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +        public static string[] Stringsplit()
Не очень хорошее название функции - должно отражать действие и быть написать в `PascalCase`. 
Более удачное название будет в духе `ReadAndSplitUserInput`, или что-то.

2022-01-27 16:10 UTC, Tauders commented on Subtasks/README.md
> +-> 2
Это что?

2022-01-27 16:10 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            string[] numbers = userInput.Split(new char[] { ' ' });
А почему это называется `numbers`? Здесь просто строки.

2022-01-27 16:10 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            string[] numbers = Stringsplit();
Почему так называется переменная?

2022-01-27 16:10 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            bool checkUserInput = false;
Название не очень. Переменная типа bool должна быть вопросом, ответ на который "да" или "нет".

2022-01-27 16:10 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            int generatedNumber = rnd.Next(3, 7);
Сделай имя более отражающим смысл.

2022-01-27 16:10 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +                    if (int.TryParse(inputNumbers, out int newInputNumbers) && newInputNumbers < generatedNumber && newInputNumbers >= 0)
Почему переменная `newInputNumbers` называется так? Там же одно число.

2022-01-27 16:21 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +            string[] numbers = userInput.Split(new char[] { ' ' });
Можешь сделать здесь сразу возврат результатов выполнения функции `Split` и не придётся заводить отдельную переменную.

2022-01-27 18:44 UTC, St1ke commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +                    total = Multiplication(choosenNumbers, counter);
ааа, не до конца понял смысл, ранее его значение используется в методе и принимается ,а тут чисто выходные и те что используются на выходе ?

2022-01-27 18:46 UTC, St1ke commented on Subtasks/Evgeniy/Subtask-2/Subtask-2/Program.cs
> +                    total = Multiplication(choosenNumbers, counter);
![image](https://user-images.githubusercontent.com/83986957/151423738-0d5b9b07-8680-4903-b572-ad59611a3d4d.png)

2022-01-27 21:25 UTC, Tauders approved these changes

2022-01-27 21:32 UTC, CodingFeles approved these changes

2022-01-27 21:33 UTC, merged