Dmitry/[Subtasks-1] Решение подзадачи 1
Tauders/denis-tasks pull request #30
Opened 2022-01-31 23:25 UTC by Shair24

2022-01-31 23:58 UTC, CodingFeles requested changes

2022-01-31 23:58 UTC, CodingFeles commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +
Лишние пустые строки.

2022-01-31 23:58 UTC, CodingFeles commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                string strLines = Console.ReadLine();
strLines - не лучшее название. Ты читаешь количество строк, а название не отражает это.

2022-01-31 23:58 UTC, CodingFeles commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                int numberLines;
Аналогично. Логика именования видна, но в итоге вариант не лучший.

2022-01-31 23:58 UTC, CodingFeles commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                    int numberingLines = 1;
```int numberLines;```
```int numberingLines = 1;```
Ситуация с названиями усугубляется ещё тем, что разные переменные схоже именуются. Сложно понимать, в чём их суть.

2022-01-31 23:58 UTC, CodingFeles commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                        Console.WriteLine("Введите строку " + (numberingLines++));
Изучи как работают префиксные и постфиксные инкременты/декременты.

2022-01-31 23:58 UTC, CodingFeles commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                        string input = Console.ReadLine();
Можно избавиться от переменной input.

2022-01-31 23:58 UTC, CodingFeles commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                    bool x = true;
x - не лучшее название переменной.

2022-01-31 23:58 UTC, CodingFeles commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                        int numberArrayIndex;
Я бы предпочёл strArrayIndex и arrayIndex, так как по сути своей индекс массива - число. Так что логично выделять отдельно только строковую форму.

2022-01-31 23:58 UTC, CodingFeles commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                        if (arrayIndex == "x")
С другой стороны, смотри здесь как читается "если индекс массива равен икс", ну, такое. Это ввод пользователя и именовать, наверное, стоит так же.

2022-01-31 23:58 UTC, CodingFeles commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                            if (int.TryParse(arrayIndex, out numberArrayIndex) && numberArrayIndex-- <= numberLines && numberArrayIndex > 0)
Аналогичная рекомендация про --.

2022-01-31 23:58 UTC, CodingFeles commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +
Поправь форматирование.

2022-02-01 00:18 UTC, CodingFeles commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                        Console.WriteLine("Введите строку " + (numberingLines++));
Забираю свой комментарий назад. Ты сделал как надо.

2022-02-01 19:46 UTC, Tauders requested changes

2022-02-01 19:46 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                    Console.WriteLine("Введите строку " + (numberingLines++));
Используй интерполяцию строк.
Попробуй избавиться от переменной `numberingLines ` - можно обойтись без неё.

2022-02-01 19:46 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                bool shutDown = true;
Переменная типа `bool` должна в идеале быть вопросом, ответ на который "да" или "нет". Здесь переменная под такое требование не подходит.

2022-02-01 19:46 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                    Console.WriteLine("Все строки введены, выберите строку для отображения");
А надо ли показывать это каждую итерацию?

2022-02-01 19:46 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                    int arrayIndex;
Мне кажется без переменной на этом уровне можно обойтись, попробуй.

2022-02-01 19:46 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +            if (int.TryParse(inputNumberLines, out int numberLines) && numberLines > 0)
Попробуй инвертировать условие, чтобы уменьшить вложенность. Здесь это не совсем тривиально, так что если не получится, то пиши.

2022-02-01 20:17 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1.sln
> +EndProject
Удали `ConsoleApp1` из решения.

2022-02-02 09:30 UTC, Tauders requested changes

2022-02-02 09:30 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                    break;
Это нормальное использование, но попробуй без `break;`

2022-02-02 09:30 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                if(inputNumberLines == "x")
А если пользователь введёт большую `X`?

2022-02-02 09:30 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                        if (inputArrayIndex == "x")
А если пользователь введёт `X`?

2022-02-02 09:30 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                                Console.WriteLine(lines[arrayIndex]);
Можно было бы не переназначать даже переменную и здесь просто обратиться `arrayIndex - 1`.

2022-02-02 17:28 UTC, Tauders requested changes

2022-02-02 17:28 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                        while (inputX)
Это, по сути, `while(true)`, не очень хорошо, но здесь, может быть, и норм.

@CodingFeles что думаешь?

2022-02-02 17:28 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                            else
А нужно ли `else`? Если выше есть `return`?

2022-02-04 18:01 UTC, Tauders requested changes

2022-02-04 18:01 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +            bool input = false;
Булева переменная должна отвечать на вопрос "да" или "нет". Отвечает ли эта переменная?

2022-02-04 18:01 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                    Console.WriteLine("Ошибка! Нужно ввести целое положительное число от 1 до N");
О каком N здесь идёт речь?

2022-02-04 18:01 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +            int numberLines = 0;
Лучше, имхо, будет `numberOfLines`

2022-02-04 18:01 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                if (int.TryParse(inputNumberLines, out numberLines))
А зачем ты убрал условие про `> 0`?

2022-02-04 18:01 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +            if (numberLines > 0)
А будет ли это вообще валидным случаем?

2022-02-04 18:01 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +            bool inputX = true;
Название.

2022-02-04 18:15 UTC, Tauders requested changes
Отформотируй документ

2022-02-04 18:15 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +            while (isInputEnded)
Название противоречит смыслу.

2022-02-04 18:15 UTC, Tauders commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +            //bool inputX = true;
Убери лишние комменты

2022-02-04 18:54 UTC, CodingFeles requested changes

2022-02-04 18:54 UTC, CodingFeles commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +            bool isInputX = true;
Исходя из названия переменной, оно должно быть изначально false. У нас же не с самого начала введено Х.

2022-02-04 18:54 UTC, CodingFeles commented on Subtasks/Dmitry/Subtask1/Subtask1/Program.cs
> +                    Console.WriteLine("Ошибка! Такой строки не существует");
Разве ошибка в несуществующей строке?

2022-02-04 19:46 UTC, CodingFeles approved these changes

2022-02-04 20:24 UTC, Tauders approved these changes

2022-02-04 20:33 UTC, merged