Evgeniy/subtask 3
Tauders/denis-tasks pull request #31
Opened 2022-02-02 09:34 UTC by St1ke

2022-02-02 09:38 UTC, Tauders requested changes
Задание сразу с звёздочкой.
Начни для `asc` и `desc` использовать Enum.

2022-02-02 09:38 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +            List<string> SetOfWords = new List<string>();
Зачем с большой буквы? Локальные переменные начинаются с маленькой.

2022-02-02 09:38 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +            string userInput = "";
Зачем эта переменная снаружи цикла?

2022-02-02 09:38 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +            bool validUserInput = false;
Не очень хорошее название - ввод то в любой случае валидный.

2022-02-02 09:38 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +            string sortSelection = Console.ReadLine();
Переделай на использование `switch-case` здесь будет чуть лучше.

2022-02-02 09:38 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +                }
Этот кусок дублируется.

2022-02-02 09:38 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +                Console.WriteLine("Вы ввели неверное значение, значит вам нужно отдохнуть и больше не вводить значений");
А разреши ещё раз вводить значение.

2022-02-04 20:32 UTC, St1ke commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +            bool validUserInput = false;
endOfCycle пойдёт сгодится?

2022-02-04 20:33 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +            bool validUserInput = false;
Лучше тогда уж `isInputEnded` или `endOfInput`.

2022-02-04 20:34 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +            bool validUserInput = false;
Лучше давать названия как можно ближе к теме происходящего.

2022-02-04 20:46 UTC, St1ke commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +                }
А что я могу с ним сделать, уже в switch/case, такой маленький кусок кода в метод чтоль?

2022-02-04 20:50 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +                }
Нет, можно иначе убрать это дублирование

2022-02-04 21:13 UTC, Tauders requested changes

2022-02-04 21:13 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +                        break;
Неверно по смыслу задачи - нигде не упоминается, что можно выйти. Если хочешь это добавить, то:
1) обсуди с нами (как с состовителями заданий)
2) поменяй название переменной
3) добавь указание пользователю на этот функционал

2022-02-04 21:15 UTC, St1ke commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +                        break;
Ты просил разрешить ещё раз вводить значение,

2022-02-04 21:18 UTC, Tauders requested changes

2022-02-04 21:18 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +                        break;
И как это связано с добавлением функции выхода?

2022-02-06 16:59 UTC, Tauders requested changes

2022-02-06 16:59 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +        }
Добавь значение по умолчанию

2022-02-06 16:59 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +        enum SortWords
Название не очень

2022-02-06 16:59 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +        enum SortWords
Перемести в отдельный файл

2022-02-06 16:59 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +                Enum.TryParse(sortSelection, out SortWords convertedSortSelection);
Убери `ToLower()` - посмотри, как можно использовать `TryParse` ещё.

2022-02-06 16:59 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +            asc,
Добавь числовые значения у них (типа `acs = 1` и т.д.), чтобы было однозначное определение.

2022-02-08 08:19 UTC, Tauders approved these changes, later dismissed

2022-02-08 08:19 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +                        break;
Не уверен, что надо обрабатывать по особому это.

2022-02-08 08:19 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +                Enum.TryParse(sortSelection, true, out SortMethod convertedSortSelection);
`convertedSortSelection` можно назвать `selectedSortMethod`

2022-02-08 08:19 UTC, Tauders commented on Subtasks/Evgeniy/Subtask-3/Subtask-3/Program.cs
> +
Добавь `Все значения выведены`.

2022-02-08 15:37 UTC, Tauders approved these changes

2022-02-08 15:57 UTC, CodingFeles approved these changes

2022-02-08 15:59 UTC, merged