Упражнение 2 - версия 1
Tauders/denis-tasks pull request #35
Opened 2022-08-17 15:47 UTC by VeronikaFront

2022-08-17 21:45 UTC, Tauders requested changes
У меня программа не работает :(

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/index.html
> +        <form action="#" class="form form1">
Зачем здесь `form1`? Если для нахождения в скрипте, то лучше id использовать, в идеале с более говорящим названием `input-word-form` или что-нибудь подобное

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/index.html
> +            <p style="margin-top:0;">Введите слово:</p>
Использовать `style` допустимо, но для целей обучения и закрепления хороших практик давай не будем. Использование `style` может привести к сложностям с пониманием кода, накладывание приоритетов в css (стиль "на месте" всегда будет приоритетнее, и тяжело понимать может быть, что и почему происходит)

Чуть больше деталей: 
https://stackoverflow.com/questions/2612483/whats-so-bad-about-in-line-css 
https://stackoverflow.com/questions/70051589/are-inline-styles-bad
https://htmlacademy.ru/blog/articles/inline

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/index.html
> +                <svg viewBox="0 0 180 65" class="border">
Не очень хорошее название класса - есть свойство `border` и его тяжело будет находить + достаточно общее и не очень понятно, что оно отображать должно.

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/index.html
> +                </svg>
Эта svg повторяется 2 раза - можно ли её убрать в файл и подключить отдельно? Здесь я не гарантирую, что это возможно, так что можно попробовать, если получится, то круто.

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/index.html
> +        <form action="#" class="form form2">
`form2` тот же коммент, как и у `form1`

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/index.html
> +            <button class="form_btn" id="sort_submit" type="submit">
А зачем здесь `id`?

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/index.html
> +                </ul>
Попробуй форматер кода автоматический, он не допустит таких странностей. Рекомендую prettier https://prettier.io/
Если используешь VSCode, то там можно добавить его из расширений и настроить форматирование по сохранению файла. Будут вопросы с этим - пиши.

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.css
> +    flex-wrap: wrap;
Может привести к странным результатам в случае добавления новых элементов

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.css
> +    width: 560px;
Можешь пока особо не запариваться, но задавать так жёстко ширину имеет далеко не всегда смысл. Обычно стараются либо сделать `min-width`, либо как-то иначе задать ширину (через падинги и маржины)

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.css
> +    transition: .3s;
Исключительно из-за производительности обычно стараются так "широко" не задавать `transition`.

Чуть подробнее, но предлагаю пока голову не забивать, просто запомнить, что анимация не "бесплатная" и может тормозить. 
https://web.dev/animations-guide/#conclusion

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.css
> +    width: 180px;
Лучше паддингами стараться задавать ширину, так кнопка будет подстраиваться под содержимое и всегда выглядеть нормально, а то сейчас при длинном тексте выглядит не очень. 
<img width="272" alt="image" src="https://user-images.githubusercontent.com/4114636/185245079-76785d86-ed9d-470a-be6d-7f8dac8b6162.png">

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.css
> +    outline: none;
Надо ли оно? Сам параметр зачастую удаляют, но вообще он несёт смысл в плане доступности. 
https://developer.mozilla.org/en-US/docs/Web/CSS/outline#accessibility_concerns

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.css
> +    background: transparent;
А нужны эти стили?

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.css
> +p {
Такое широкое задание (по тегу) может к максимально странным вещам привести, так что не очень рекомендуется использовать.

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/index.html
> +            <p>Отсортируйте результаты:</p>
А почему не `h..` какого-нибудь уровня?

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/index.html
> +            <p style="margin-top:0;">Введите слово:</p>
А почему не `h..` какого-нибудь уровня?

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.css
> +    outline:none;
Попробуй авто-форматирование стиля кода. Нужен ли `outline`?

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.css
> +.block_results p{
Надо ли так широко `p`?

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.css
> +.block_results {
У тебя сверху уже есть `block_results`.

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.css
> +.block_results>div {
Такое сильно может непредсказуемо поменять стили, при изменении вёрстки.

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +let sortList = document.getElementById('sort_results-list');
Почему `let`, а не `const`?

https://sandrig.gitbooks.io/frontend-handbook/content/interview/javascript/chto-takoe-var-let-const-v-chem-raznitsa.html

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    if(document.querySelectorAll('.sort_results-item').length != 0){
Стоит выносить повторяющиеся (да и не только) селекторы в константы, так их потом проще менять и находить

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    if(document.querySelectorAll('.sort_results-item').length != 0){
Не стоит использовать `!=` лучше `!==` 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +document.querySelector(".form1").addEventListener('submit', function (e) {
`form1` почему-то в двойных кавычках, а почти всё остальное в одинарных.

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    let inputItem = document.createElement('li');
`let` -> `const`

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    inputItem.className = 'input_results-item';
Хорошо бы сдвинуть имя класса в константу.

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +let sortList = document.getElementById('sort_results-list');
А зачем это за пределами функции?

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +let radioAscending = document.getElementById('sort_ascending');
А зачем это за пределами функции?

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    }
Форматирование. Можно добавить `else if`.

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    resultsArray = resultsArray.map(t => { return t.innerText })
Пожалуйста не меняй тип массива таким образом, было `Element`, стало `string`

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    if(document.querySelectorAll('.sort_results-item').length != 0){
Те же комментарии, что и к прошлому месту.

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +      });
Вкусовщина, но попробуй `for..of`.

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    resultsArray.forEach(function(item) {
`item` не очень хорошее название, можем лучше `result`?

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    let inputItem = document.querySelectorAll('.input_results-item');
Название не очень хорошее. `inputItem` значит что-то одиночное.

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    let resultsArray = Array.from(inputItem);
Название не очень хорошее.

2022-08-17 21:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    resultsArray = resultsArray.map(t => { return t.innerText })
Можно объединить в `Array.from(inputItem).map(t=>t.innerText)` и получить сразу массив строк

2022-08-21 14:22 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-2/index.html
> +                </svg>
Это эффект для бордера у кнопки, у меня не получилось корректно отобразить его другими способами.

2022-08-21 14:23 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-2/main.css
> +    flex-wrap: wrap;
Что-то я не поняла, что ты имеешь ввиду.

2022-08-21 14:24 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-2/main.css
> +    transition: .3s;
Исправлять не стала, изучу материалы.

2022-08-21 14:24 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-2/main.css
> +    background: transparent;
Эти стили создают эффект при наведении у кнопки.

2022-08-21 14:27 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +let sortList = document.getElementById('sort_results-list');
Так как эти переменные используются в обеих функциях. Чтобы не задавать их значение 2 раза.

2022-08-21 16:04 UTC, VladimirAsmolovskiyQs commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +let sortList = document.getElementById('sort_results-list');
`inputList` не используется во второй

2022-08-21 16:04 UTC, VladimirAsmolovskiyQs commented on SubtasksJs/Nika/SubtaskJS-2/index.html
> +                </svg>
Окей

2022-08-21 16:06 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/index.html
> +                </svg>
Окей

2022-08-21 16:07 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.css
> +    flex-wrap: wrap;
Я про то, что такое использование могло привести к странным результатам, если элементов будет много добавлено и они будут "оборачиваться"

2022-08-21 16:07 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.css
> +    transition: .3s;
Окей

2022-08-21 16:07 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.css
> +    background: transparent;
Окей

2022-08-21 16:07 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +let sortList = document.getElementById('sort_results-list');
`inputList` не используется

2022-08-21 16:34 UTC, Tauders requested changes

2022-08-21 16:34 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +const sortList = document.getElementById('sort_results-list');
Название не очень - по внешнему виду, выглядит, как функция `sortList`. Название функции это глагол, типа "что сделать" или "что делает". "Отсортировать массив" или "Отсортировать список"

2022-08-21 16:34 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    const sortCollectionItems = document.querySelectorAll('.sort_results-item');
Название не очень, выглядит, как название функции

2022-08-21 16:34 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    const passValue = document.querySelector('.form_data').value;
Название не очень, выглядит как функция

2022-08-21 16:34 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    const inputItem = document.createElement('li');
А почему `li` это `inputItem`?

2022-08-21 16:34 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    const passValue = document.querySelector('.form_data').value;
Не очень хороший селектор - он возвращает первый элемент с таким классом. А если появится другой элемент на странице, раньше, чем этот, с таким же классом. 
Лучше здесь обратиться напрямую к `input` элементу, по `id`

2022-08-21 16:34 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    const radioDescending = document.getElementById('sort_descending');
Можно добавить на конце названия переменной `Option` - будет понятнее. 
`radioDescendingOption`

2022-08-21 16:34 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    const sortCollectionItems = document.querySelectorAll('.sort_results-item');
Название

2022-08-21 16:34 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    let inputArrayItems = Array.from(inputCollectionItems).map(t=>t.innerText);
`let` -> `const`

2022-08-21 16:34 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +        const sortItem  = document.createElement('li');
Название переменной.

2022-08-24 07:24 UTC, Tauders requested changes

2022-08-24 07:24 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    const outputListItemClassName = 'input_results-item';
Сделай это тоже константой

2022-08-24 07:24 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    const radioAscendingOption = document.getElementById('sort_ascending');
Тоже в константы

2022-08-24 07:24 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +      const itemSortedListClassName = 'sort_results-item';
Константа

2022-08-24 07:24 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    for (let result of itemsArrayOutputListItems) {
`let` -> `const`

2022-08-24 19:20 UTC, Tauders submitted a review, later dismissed

2022-08-24 19:20 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    const outputListItemTagName = 'li';
Это можно оставить на месте :D Так как это всегда идёт в связке с `createElement` и он принимает только определённые параметры.

2022-08-24 19:20 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    const outputListItemClassName = 'input_results-item';
Можно убрать наверх файла

2022-08-24 19:20 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    const radioAscendingOptionID = 'sort_ascending';
Можно убрать наверх файла

2022-08-24 19:20 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +    const radioDescendingOptioniD = 'sort_descending';
`iD` -> `ID`

2022-08-24 19:20 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +      const itemSortedListTagName = 'li';
Можно не выносить.

2022-08-24 19:20 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +      const itemSortedListClassName = 'sort_results-item';
Можно убрать наверх

2022-08-26 07:04 UTC, Tauders submitted a review, later dismissed

2022-08-26 07:04 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +
Пустые строки лишние

2022-08-26 07:04 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-2/main.js
> +
Пустая строка

2022-08-26 17:12 UTC, Tauders approved these changes

2022-08-26 17:13 UTC, merged