Упражнение 3
Tauders/denis-tasks pull request #37
Opened 2022-08-24 15:07 UTC by VeronikaFront

2022-08-24 19:38 UTC, Tauders requested changes

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.css
> +input[type='radio']:focus-visible {
Лучше классами делать первую часть, так как это сильно общий селектор

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.css
> +#form_page h2 {
h2 можно поменять на класс

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.css
> +.block_results h3 {
h3 можно поменять на класс

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.css
> +  color: rgb(255, 255, 255);
А почему здесь `rgb`, а обычно hex?

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.css
> +.control label {
label можно поменять на класс

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.css
> +  vertical-align: middle;
Нужны ли все эти параметры вместе?

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.css
> +input[type='radio'] {
Опять же, лучше на класс, и лучше такие вещи держать вместе, чуть более очевидно.

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.css
> +#checkboxList label {
label лучше на класс

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    const errorBoxClassName = '.error--box';
Можно убрать наверх

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    if (arrayEnteredValues.length >= 20) {
С таким большим количеством вложенных `if` тяжело что-то понимать, так что это надо убирать и разбивать на мелкие функции.

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +      errorBox.append(error);
Можно вынести здание ошибки в отдельную функцию.

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +      for (let enteredValue of arrayEnteredValues) {
`let`->`const`

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    } else {
Можно убрать в функцию

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +      for (let enteredValue of arrayEnteredValues) {
Можно валидацию каждой числа убрать в функцию

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +          continue;
Можно заранее убрать пустые значения

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +          checkboxItem.className = 'checkbox';
Можно убрать в константу

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +          checkboxItem.id = enteredValue;
Убрать генерацию элементов можно в функцию

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    const checkboxElementsClassName = '#checkboxList label input';
Можно убрать в константы

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    }
Почему бы не `for ... of`?

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    }
Можно оставить здесь только вычисление, а присвоение и сброс радио батонов после.

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +        (division, current) => division / current
А если на 0?

2022-08-24 19:38 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    }
Можно убрать вычисление убрать в отдельную функцию.

2022-08-26 20:19 UTC, Tauders requested changes

2022-08-26 20:19 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    }
Надо вынести за пределы функции

2022-08-26 20:19 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +        });
Можно чуть проще написать через стрелочную функцию, попробуй.

2022-08-26 20:19 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    function performСalculationOperation(error) {
Вынеси за пределы функции

2022-08-26 20:19 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +          return (error = '');
А это зачем?

2022-08-26 20:19 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +      } else if (radioSubtractionOption.checked) {
А нужно `else if`?

2022-08-26 20:19 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +          } else {
А нужно ли здесь `if ... else`? если ты каждое выражение заканчиваешь `break;` или `continue;`?

2022-08-26 20:19 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +      function CheckEnteredValues() {
Вынеси функцию наружу

2022-08-26 20:19 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +            function createCheckboxItem() {
Вынеси функцию наружу

2022-08-26 20:19 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    const checkboxElementsClassName = '#checkboxList label input';
А почему имя класса начинается `#`?

2022-08-28 08:20 UTC, Tauders requested changes

2022-08-28 08:20 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +        }
Вынеси эту функцию ещё выше.

2022-08-28 08:20 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +          checkboxItem.id = enteredValue;
зачем ему такое id?

2022-08-28 08:20 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +  function division() {
Вынеси эти функции выше, добавь параметры массива для вычисления, пусть возвращает число.

2022-08-28 08:20 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    function CheckEnteredValues() {
Вынеси функцию выше. Пусть она занимается только валидацией, то есть если всё хорошо, она вернёт `true`, если нет, ошибку. 
Почему эта функция с большое буквы?

2022-08-28 08:20 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +      for (const enteredValue of arrayEnteredValues) {
Создай функцию валидация каждого значения.

2022-08-28 08:20 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    if (arrayEnteredValues.length >= 20) {
Эту проверку можно убрать в `CheckEnteredValues`

2022-08-28 08:20 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +const radioDivisionOption = document.getElementById(radioDivisionOptionID);
Зачем это снаружи функции?

2022-08-28 08:20 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    case 3:
0, 1, 2, 3 плохие названия для определения, что ты хочешь сделать, они называются "магические числа" https://ru.wikipedia.org/wiki/Магическое_число_(программирование)
Сделай константы с определением, что они значат. 
Или ещё лучше, пусть возвращается более осмысленное название.

2022-08-28 08:20 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +  const controlRadioOptionIndex = defineIndex();
`defineIndex` означает "определить индекс", а здесь ты не то делаешь, не очень хорошее название

2022-08-28 08:38 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +  const controlRadioOptionIndex = defineIndex();
Он определяет индекс кнопки, что значит, не то делаю?

2022-08-28 08:40 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    case 3:
Это индекс.  я вверху передаю переменную, которая его содержит, 1,2,3 - это значение переменной

2022-08-28 08:41 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +  const controlRadioOptionIndex = defineIndex();
Он его не определяет, он его находит или берёт у радио батона. Define не значит взять готовое, а значит задать что-то.

2022-08-28 08:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    case 3:
Я понимаю, но даже так это плохие названия. Можно либо вынести индекс в переменные, чтобы было понятно, либо (лучше) возвращать не индекс, а конкретные действия. 

```
const ADDITIONAL_INDEX_ACTION = 0;
...

case ADDITIONAL_INDEX_ACTION:
```

Название можно поменять. 

А если бы был лучший вариант, то была бы функция, которая возвращает одно из действий уже. 

```
const action = getNeededAction();

switch (action) {
  case 'addition': 
  {
...
```

2022-08-28 17:16 UTC, Tauders requested changes

2022-08-28 17:16 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    function createCheckboxItem(enteredValue) {
Всё ещё вынеси выше функцию, за пределы этого `eventListener`

2022-08-28 17:16 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    function checkEnteredValue(enteredValue) {
Всё ещё вынеси выше функцию, за пределы этого `eventListener`

2022-08-28 17:16 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +        return;
Желательно вернуть `return false;`

2022-08-28 17:16 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +        } else return;
Лучше оставить `{}` и возвращать значение - лучше `return false;`

2022-08-28 17:16 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +          clearErrorboxSheet();
А зачем делать на каждое валидное значение?

2022-08-28 17:16 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +  }
Лучше просто найти этот index и вернуть из отдельной функции.

2022-08-28 17:16 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +      ? 'division'
Всё ещё есть магические числа, нужно убрать. Такие длинные тернарные операции плохо понимаются, лучше не делать так. 

Почему бы не попробовать сделать у checkbox `value` подходящий?

2022-08-28 17:16 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +}
Пусть возвращают значение после вычисления в массиве.

2022-08-28 21:01 UTC, Tauders requested changes

2022-08-28 21:01 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +  });
Унеси эту функцию вниз, так как теперь становится не очень понятно, что и как связано, пусть "подписки" и "event listener'ы" будут внизу

2022-08-28 21:01 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +}
Эта функция никогда не возвращает "true" - почему?

2022-08-28 21:01 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +  clearErrorboxSheet();
Почему мы сначала добавляем ошибку, а потом чистим поле для ошибок?

2022-08-28 21:01 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +  clearErrorboxSheet();
Что значит `ErrorboxSheet`?

2022-08-28 21:01 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +      countingResults.innerHTML = division(arrayEnteredValuesChecked);
Может стоит вынести вычисление в отдельную переменную и просто потом назначить эту переменную в итог? Так, кажется, будет проще выглядеть.

2022-08-28 21:01 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +      countingResults.innerHTML = division(arrayEnteredValuesChecked);
А если здесь ничего не вернётся?

2022-08-28 21:01 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +  const action = determineValueSelectedRadioOption();
Лучше `get` вместо `determine`.

2022-08-28 21:01 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +  }
Конвертируй в for..of?

2022-08-28 21:01 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +}
Лучше вынеси отображение ошибки и очистку результатов за пределы функции. В идеале функция выполняет 1 функцию и отвечает на вопрос глагола. 
У тебя же функция делает несколько вещей.

2022-08-28 21:01 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    clearResultsBlock();
А почему мы только здесь очищает результат?

2022-08-28 21:01 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +  clearErrorboxSheet();
А почему мы только здесь очищаем ошибки?

2022-08-28 21:01 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +  }
Вынеси switch..case в отдельную функцию.

2022-08-28 21:01 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +function performСalculationOperation() {
А ты уверена, что эта функция в таком виде нужна? Здесь всё в перемешку - данные берутся из документа, валидация, выполнение действий. 
Мне кажется можно это оставить в главной функции. Или разбить маленький части каждые на отдельные функции и вызывать их из главной функции.

2022-08-28 21:01 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    clearErrorboxSheet();
Что здесь значит `sheet`?

2022-08-28 21:01 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +}
Почему `clearCheckboxSheet` выполняется не во всех случаях?

2022-08-28 21:10 UTC, Tauders requested changes

2022-08-28 21:10 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +  if (arrayEnteredValues.length >= 20) {
Вынеси `20` в константу (раньше я упускал что-то этот момент)

2022-08-28 21:10 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +  if (enteredValue.length >= 20) {
Вынеси `20` в константы.

2022-08-29 06:44 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +      countingResults.innerHTML = division(arrayEnteredValuesChecked);
Что ты имеешь ввиду? 
Если не один из кейсов не подойдет?

2022-08-29 08:15 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +      countingResults.innerHTML = division(arrayEnteredValuesChecked);
Нет, это только к последней операции. `division` может ничего не вернуть, судя по коду

2022-08-29 10:56 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    clearErrorboxSheet();
Тут про последнюю строку, или про оба?

2022-08-29 10:58 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    clearErrorboxSheet();
Последнюю изменила, первая означает "очистка листа чекбоксов" , я не знаток английского, но гугл переводит верно

2022-08-29 11:45 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    clearErrorboxSheet();
А чем `clearCheckboxList()` не подходит?

2022-08-29 11:56 UTC, Tauders approved these changes, later dismissed

2022-08-29 11:56 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +        calculationResults = '';
А почему здесь `calculationResults` строка, а в других местах число? Может лучше возвращать `undefined`?

2022-08-29 11:56 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    return createError('Для выполнения операций выберите числа!');
А зачем здесь `return`?

2022-08-29 11:56 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +      'Вы ввели слишком длинное число! Максимально разрешенная  длина числа - 20 знаков.'
`разрешенная  длина` - 2 пробела подряд

2022-08-29 11:56 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +function checkEnteredValue(enteredValue) {
Можно назвать `validateEnteredValue`

2022-08-29 11:56 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    }
Можно инвертировать и будет меньше вложенности:

```ts
    if (!checkEnteredValue(enteredValue)) {
      clearCheckboxSheet();
      return false;
    }

    createCheckboxItem(enteredValue);
```

2022-08-29 11:56 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +      calculationResults = '';
Почему строка, а обычно число? Может лучше возвращать `undefined`?

2022-08-29 16:20 UTC, Tauders requested changes

2022-08-29 16:20 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-3/main.js
> +    if (performSelectedAction(arrayEnteredValuesChecked) != undefined) {
Лучше `!==` - так проверка строже. https://ru.stackoverflow.com/questions/431662/В-чем-разница-между-и

2022-08-29 17:21 UTC, Tauders approved these changes

2022-08-29 17:22 UTC, merged