Добавил описание подзадачи 4 и 5 для фронта
Tauders/denis-tasks pull request #38
Opened 2022-08-26 08:31 UTC by Tauders

2022-08-26 14:10 UTC, CodingFeles requested changes
4я - норм. 5я - понятен результат и смысл, но какой порядок действий для ввода и запуска алгоритма не очень очевидно.

2022-08-26 14:10 UTC, CodingFeles commented on SubtasksJs/README.md
> +3. Вывести ниже формы ввода все уникальные числе, среднее арифметическое, самое большое и маленькое.
> числе

опечаточка.

2022-08-26 14:10 UTC, CodingFeles commented on SubtasksJs/README.md
> +2. Пользователь вводит количество групп во второую форму для ввода.
> второую

опечаточка.

2022-08-26 14:10 UTC, CodingFeles commented on SubtasksJs/README.md
> +3. Вывести случайно разбитые на нужное количество групп строки. Примерно одинаково количество строк в группах. Для этого сделать динамическое появление нужного количества столбцов внизу страницы с вх
> одинаково

опечаточка.

2022-08-26 14:10 UTC, CodingFeles commented on SubtasksJs/README.md
> +Если будет желание, можно чуть усложнить задачу и сделать, чтобы случайным образом выбиралась название этой группы и добавлялось, как заголовок столбца.
> выбиралась

опечаточка.

2022-08-26 14:10 UTC, CodingFeles commented on SubtasksJs/README.md
> +Если будет желание, можно чуть усложнить задачу и сделать, чтобы случайным образом выбиралась название этой группы и добавлялось, как заголовок столбца.
> и добавлялось, как

вроде запятая не нужна.

2022-08-26 14:10 UTC, CodingFeles commented on SubtasksJs/README.md
> +1. Пользователь вводит произвольное число строк в первую форму для ввода (через enter или нажатие на кнопку).
Строки построчно сабмитятся? Тогда как отображаются уже введённые строки?
Или там мультистроковой инпут, но тогда нажатие на кнопку сбивает с толку?

2022-08-26 14:10 UTC, CodingFeles commented on SubtasksJs/README.md
> +3. Вывести случайно разбитые на нужное количество групп строки. Примерно одинаково количество строк в группах. Для этого сделать динамическое появление нужного количества столбцов внизу страницы с вх
> Вывести

В какой момент? По нажатию на отдельную кнопку? Или при добавлении каждой новой строки мы перераспределяем по группам заного? Или добавляем новую строку к одной из уже существующих групп?

2022-08-26 17:08 UTC, Tauders commented on SubtasksJs/README.md
> +3. Вывести случайно разбитые на нужное количество групп строки. Примерно одинаково количество строк в группах. Для этого сделать динамическое появление нужного количества столбцов внизу страницы с вх
> > одинаково
> 
> опечаточка.

какая?
<img width="779" alt="image" src="https://user-images.githubusercontent.com/4114636/186956751-4eb5a447-fa03-4c27-9c61-13b6e96c57f4.png">
https://kakpishem.ru/pishem-pravilno-slova/odinakovo-ili-odinakogo-kak-pishetsya.html

Или не про то думаю?

2022-08-26 17:08 UTC, Tauders commented on SubtasksJs/README.md
> +3. Вывести случайно разбитые на нужное количество групп строки. Примерно одинаково количество строк в группах. Для этого сделать динамическое появление нужного количества столбцов внизу страницы с вх
> > Вывести
> 
> В какой момент? По нажатию на отдельную кнопку? Или при добавлении каждой новой строки мы перераспределяем по группам заного? Или добавляем новую строку к одной из уже существующих групп?

По нажатию, добавлю

2022-08-26 17:09 UTC, Tauders commented on SubtasksJs/README.md
> +Если будет желание, можно чуть усложнить задачу и сделать, чтобы случайным образом выбиралась название этой группы и добавлялось, как заголовок столбца.
> > и добавлялось, как
> 
> вроде запятая не нужна.

я не спец, надо консультацию взять :D но хз, у кого

2022-08-26 17:14 UTC, Tauders commented on SubtasksJs/README.md
> +1. Пользователь вводит произвольное число строк в первую форму для ввода (через enter или нажатие на кнопку).
> Строки построчно сабмитятся? Тогда как отображаются уже введённые строки?
> Или там мультистроковой инпут, но тогда нажатие на кнопку сбивает с толку?

да, построчно, внизу в колонке, добавлю это

2022-08-26 17:21 UTC, Tauders commented on SubtasksJs/README.md
> +Если будет желание, можно чуть усложнить задачу и сделать, чтобы случайным образом выбиралась название этой группы и добавлялось, как заголовок столбца.
Я получил консультацию, там она нужна.

2022-08-27 08:35 UTC, CodingFeles approved these changes
ЛГТМ

2022-08-27 08:35 UTC, merged