Упражнение 4
Tauders/denis-tasks pull request #40
Opened 2022-08-29 16:08 UTC by VeronikaFront

2022-08-29 19:58 UTC, Tauders requested changes

2022-08-29 19:58 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-4/main.js
> +    createError('Необходимо ввести число в диапазоне [10; 1000]');
Но ведь нельзя ввести 10 и 1000

2022-08-29 19:58 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-4/main.js
> +  return Math.ceil(100 * Math.random());
Почему ceil, а не round?

2022-08-29 19:58 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-4/main.js
> +  return additionRandomlyGeneratedNumbers(arrayRandomlyGeneratedNumbers) / 2;
Почему деление на 2, а не количество чисел?

2022-08-29 19:58 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-4/main.js
> +function calculateMinimumNumbers(arrayRandomlyGeneratedNumbers) {
Название говорит о "числах", а возвращается 1 число

2022-08-29 19:58 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-4/main.js
> +function calculateMaximumNumbers(arrayRandomlyGeneratedNumbers) {
Так же, числа

2022-08-29 21:03 UTC, Tauders requested changes

2022-08-29 21:03 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-4/main.js
> +  clearErrorbox();
Почему валидация очищает ошибки?

2022-08-29 21:03 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-4/main.js
> +    return false;
Зачем возвращать `false`?

2022-08-30 12:46 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-4/main.js
> +    createError('Необходимо ввести число в диапазоне [10; 1000]');
Это еще почему?

2022-08-30 12:48 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-4/main.js
> +    createError('Необходимо ввести число в диапазоне [10; 1000]');
Ошибка выдается если число меньше 10 или больше 1000, в противном случае нет ошибки, почему нельзя ?

2022-08-30 12:50 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-4/main.js
> +    createError('Необходимо ввести число в диапазоне [10; 1000]');
А, я ошибся. Сори

2022-08-30 15:49 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-4/main.js
> +  return Math.ceil(100 * Math.random());
Чтобы исключить вероятность возвращения 0. По условию случайное число должно быть от 1 до 100.

2022-08-30 16:03 UTC, VladimirAsmolovskiyQs commented on SubtasksJs/Nika/SubtaskJS-4/main.js
> +  return Math.ceil(100 * Math.random());
А, окей

2022-08-30 16:04 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-4/main.js
> +  return Math.ceil(100 * Math.random());
А, окей

2022-08-30 18:16 UTC, Tauders requested changes

2022-08-30 18:16 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-4/main.js
> +    +enteredValue
А почему бы не использовать `arrayRandomlyGeneratedNumbers.length`?

2022-08-31 18:06 UTC, Tauders approved these changes

2022-08-31 18:52 UTC, merged