Упражнение 5
Tauders/denis-tasks pull request #41
Opened 2023-04-02 12:19 UTC by VeronikaFront

2023-04-10 20:53 UTC, Tauders requested changes
Разбей js файл на вспомогательные функции и основной файл

2023-04-10 20:53 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  resultInputBox.className = 'result-input--box';
А почему это не в константах?

2023-04-10 20:53 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  if (document.querySelector(resultsInputClassName)) {
А почему не
```
  const element = document.querySelector(resultsInputClassName);

  if (element) {
    element.remove();
  }
  ```
  ?

2023-04-10 20:53 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +function shuffleArrayEnteredStrings(arrayEnteredStrings) {
Кажется, ты здесь мутируешь оригинальный массив, а тебе это здесь надо? Его можно скопировать 
```
const newArray = [...arrayEnteredStrings];
```

2023-04-10 20:53 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  if (enteredValuesString == '') {
Лучше использовать `===` - так будет более точное сравнение

2023-04-10 20:53 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +    numberOfGroups == 0 ||
Лучше больше 0, так как сейчас можно ввести отрицательное значение

2023-04-10 20:53 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +    !(typeof +numberOfGroups != Number)
Такое сравнение будет всегда `true` так как ты кастуешь через `+` уже к числу. Тип не `Number`, а `"number"` так как typeof возвращает строку

2023-04-10 20:53 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  const arrayEnteredStrings = document
Надо обработать пустые строки, так как сейчас валидный ввод это `,,,,,,,,,,,,,`

2023-04-10 20:53 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  arrayWithSubarraysEnteredStrings
А зачем здесь этот массив? Может проще создавать его внутри?

2023-04-10 20:53 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +    numberOfGroups = +jumbledArrayEnteredStringsCopy.length;
Здесь не нужно `+` так как это всегда число

2023-04-10 20:53 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  const remainderOfJumbledArrayEnteredStrings =
Почему называется Strings, если это число?

2023-04-10 20:53 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  jumbledArrayEnteredStringsCopy,
Почему это называется копия?

2023-04-10 20:53 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  const remainderOfJumbledArrayEnteredStrings =
А зачем это вообще нужно?

2023-04-10 20:53 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +      if (headingItems[i].value == '') {
А может это проверку сдвинуть ДО создания элементов?

2023-04-10 20:53 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +        return createError(distributionStringsIntoForm, 'Введите не пустые значения заголовков!');
Здесь лучше сначала вызвать `createError`, а потом `return`, так как `createError` ничего не возвращает.

2023-04-10 20:53 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +    return createError(
Зачем возвращать `createError`?

2023-04-10 20:53 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  splitAnArrayIntoSubarrays(
Может лучше возвращать саб массивы?

2023-04-10 20:53 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +function createInputsForHeaders(arrayWithSubarraysEnteredStrings) {
Может лучше передавать сюда число строк?

2023-04-10 20:53 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  document.querySelector(buttonHeadersEntryClassName).addEventListener('click', (e) => {
А зачем это в функции?

2023-04-11 15:52 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  resultInputBox.className = 'result-input--box';
Вообще у меня уже вынесен этот класс в константу, но с точкой, так как чаще используется, а этот метод применяется один раз, поэтому я не стала его выносить.
Предполагаю, что следующим требованием будет вынести эту константу наверх, но так как по своему смыслу она содержит тоже самое, пока объявлю ее в области видимости функции, но если критично переименую тогда и вынесу.

2023-04-11 16:15 UTC, seal-developer commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +    !(typeof +numberOfGroups != Number)
Второе уточнение хорошее, но как оказалось, эта часть проверки вообще не нужна, достаточно предыдущей, она же уже на число проверяет

2023-04-11 16:25 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +function shuffleArrayEnteredStrings(arrayEnteredStrings) {
А почему нет, я его потом нигде не использую, а использую уже в перемешанном виде. 
Я понимаю, что это может обернуться жопкой, когда задача больше, но в данном случае я же знаю, что он не нужен будет более.
Может,это как минимум хорошее правило, переписала в общем

2023-04-11 16:28 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +function createInputsForHeaders(arrayWithSubarraysEnteredStrings) {
А зачем? У меня заголовки для сформированных групп, а не для каждой строки, это же разное кол-во, ну либо я не поняла тебя

2023-04-11 16:34 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  document.querySelector(buttonHeadersEntryClassName).addEventListener('click', (e) => {
Я тут не поняла, что ты конкретно выделил, если создание заголовков, то они должны создаваться только если группы сформированы, что происходит в этой функции. 
Если про другой обработчик, то тут как бы тоже он нужен, только в этих условиях, и если вынесу, надо проверять, а есть ли вообще этот элемент, стоит ли оно того, если опять же используется только при этом условии?
Почему это плохо, если это часть процесса формирования групп?

2023-04-11 16:40 UTC, VeronikaFront commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  const remainderOfJumbledArrayEnteredStrings =
Вообще название переводится, как остаток от строк, и по идее остаток может быть числом, мой английский очень хорош..
Можно переименовать в количество оставшихся строк, чтобы точно было. 
Нужно это в тех случаях, когда количество строк не может равномерно распределиться на заданное количество групп, и эти оставшиеся строки надо раскидать, куда хватит. 
Не претендую на элегантность решения, но до чего додумалась

2023-04-11 18:51 UTC, VeronikaFront commented
"Разбей js файл на вспомогательные функции и основной файл"
На модули имеешь ввиду?

2023-04-15 18:09 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  resultInputBox.className = 'result-input--box';
Я удивился, так как у тебя есть переменная за пределами функции 
```ts
const resultsInputClassName = '.result-input--box';
```
но почему-то 
```ts
result-input--box
```
у тебя только внутри функции. 

Вот из-за этого и написал - я думаю стоит вынести за пределы функции, так как у тебя она там уже, по сути есть, и получается непонятно, откуда берётся селектор, если не искать по файлу.

2023-04-15 18:12 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  const remainderOfJumbledArrayEnteredStrings =
Я понял по предназначению, я имел ввиду, что тогда лучше было было `numberOfRemainingOfJumbledArrayEnteredStrings`, может быть `numberOfRemainingNotDistributedStrings` или `numberOfNotDistributedRemainingStrings`, `numberOfRemainingString`.

2023-04-15 18:13 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +function createInputsForHeaders(arrayWithSubarraysEnteredStrings) {
Потому что внутри сам массив никак не используется, кроме как взять длину массива. А когда передаёшь структуру (массив, объект) создаётся впечатление, что там от него что-то будет использоваться, а здесь это не тот случай.

2023-04-15 18:21 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  document.querySelector(buttonHeadersEntryClassName).addEventListener('click', (e) => {
Я выделил добавление обработчика, так как это не зависит от функции сабмита напрямую.
Мне кажется, лучше проверять снаружи (хотя, по идее, там же и не на что будет привязываться). Посмотрев код ещё раз, может и нет смысла выносить наружу, но стоит переместить в `createInputsForHeaders`, так как сейчас связь супер неочевидна. 
Из потенциальных проблем, за чем надо проследить, если вызывать подписку на событие много раз и не отписываться (здесь это скорее всего не будет, так как элемент создаётся заново), то могут происходить странные баги.

2023-04-15 18:23 UTC, Tauders commented
> "Разбей js файл на вспомогательные функции и основной файл" На модули имеешь ввиду?

Я имею в виду на разные файлы, можешь сделать файл для констант, подписок на элементы и вспомогательные функции, которые не привязаны строго к текущей логике.

2023-04-15 18:54 UTC, Tauders requested changes

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.css
> +.results--title {
А это используется? Проверь другие классы и элементы?

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.css
> +  font-size: 15px;
В целом безразлично в этом случае и не обязательно менять, но обычно размеры шрифта меняются на чётные числа, типа 12-14-16.

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +    const error = document.createElement('span');
Может лучше будет `errorElement`, чтобы было понятно, о чём это?

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +function createError(parentSelector, text) {
Может это не `parentSelector`, а `parentElement`? И `errorText`, а не `text`?

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +    error.innerHTML = text;
А может лучше `innerText`?

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +function clearErrorbox(parentSelector) {
Может лучше `parentElement`?

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +    errorBox.innerHTML = '';
Опять же, может лучше `innerText`? Или вообще ставить его `visibility`?

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  const resultsInputClassName = 'result-input--box';
Лучше не переопределять константы локально, так как может возникнуть проблемы потом с пониманием, откуда берутся данные и неожиданные результаты получать.

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  const resultInputBox = document.createElement('div');
А почему это `InputBox`, если это `div`?

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +function shuffleArrayEnteredStrings(arrayEnteredStrings) {
Да, здесь просто случай, что ИЛИ мутируешь, ИЛИ новый возвращаешь, совмещение обычно путает и вызывает неожиданный результат.

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +function shuffleArrayEnteredStrings(arrayEnteredStrings) {
Если возвращаешь результат, то можно `getShuffledArrayOfEnteredStrings` или просто `getShuffledStrings`. Можно вместо входного параметра просто `strings`.

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  jumbledArrayEnteredStringsCopy,
И всё же, почему?

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +function distributeIntoGroupsRemainderOfJumbledArrayEnteredStrings(
Может лучше `distributeStringsToGroups`?

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +    arrayWithSubarraysEnteredStrings[i].push(jumbledArrayEnteredStringsCopy[i]);
Может и здесь добавить рандома? Чтобы не в первые группы добавлялись строки?

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  arrayWithSubarraysEnteredStrings
?

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +    stringList.className = 'string--list';
Этот класс есть уже в константе, почему бы не использовать и здесь?

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +    const groups = document.querySelectorAll('.string--list');
Почему здесь не константа?

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  for (let i = 0; i < arrayEnteredStrings.length; i++){
Можно использовать `for..of` или даже использовать `filter` (но чуть менее производительно)

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  if (enteredValuesString === '') {
Может надо ещё трим делать?

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +    numberOfGroups == '' ||
Используй лучше `===`.

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +    numberOfGroups <= 0 ||
А не надо тут кастовать к числу?

2023-04-15 18:54 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/main.js
> +  if (document.querySelector(resultsInputClassName) == null) {
В целом лучше использовать `===`

2023-04-22 23:49 UTC, Tauders requested changes

2023-04-22 23:49 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/js/groupHeaders.js
> +function createInputsForHeaders(arrayIntoSubarrays) {
Опять же, здесь можно использовать просто число, так как эта функция напрямую несвязана с массивом.

2023-04-22 23:49 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/js/const.js
> +const formInputString = document.getElementById(formInputStringID);
Я не уверен, что элементы, которые динамически берутся со страницы, можно назвать константами, может стоит либо выделить в отдельный файл, либо получать эти данные по местам, где они нужны, в зависимости от случаев.

2023-04-22 23:49 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/js/stringDistributionHandler.js
> +    numberOfGroups <= 0 ||
Может всё же стоит скастовать к числу, чтобы сравнивать с числом?

2023-04-22 23:49 UTC, Tauders commented on SubtasksJs/Nika/SubtaskJS-5/js/stringInputHandler.js
> +    if (string === '') {
Может надо делать trim?

2023-04-29 13:40 UTC, Tauders approved these changes

2023-04-29 16:57 UTC, merged