Задание 1 - этап 2
Tauders/denis-tasks pull request #45
Opened 2024-05-07 08:04 UTC by VeronikaFront

Добавила возможность удаления/добавления задачи.

2024-05-10 21:52 UTC, Tauders requested changes
Есть бага, что если ты напечатаешь один символ в название, то он неправильно обновит статус выключено. Посмотри на useState и принцип его работы

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/.prettierrc.json
> +}
Не хватает пустой строки в конце файла

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Button/Button.tsx
> +    : classes.button;
Здесь можно использовать библиотеку `classnames`, чтобы упростить условие

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Button/Button.tsx
> +  disabled,
Здесь спорно, так что оставь, как нравится, но, в целом, считается хорошей практикой делать такие название булевых переменных, которые сами содержат ответ на вопрос, на который можно ответить "да" или "нет". Например на вопрос "isDisabled" можно ответить "да" или "нет". 
Здесь спорно, конкретно, потому что `disabled` это дефолтный атрибут в html и здесь это может быть допустимо.

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Button/Button.tsx
> +  onKeyDown?: React.FormEventHandler<Element>;
А почему здесь `FormEventHandler`? Можно ли здесь указать более конкретный тип, а не `Element`? (например `HTMLButtonElement`), и почему бы не указать его?

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Button/Button.tsx
> +    ? className + ' ' + classes.button
Вот это проще сделать через [Template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Card/Card.tsx
> +  const deleteCard: React.MouseEventHandler = () => {
Здесь можно применить хорошую практику (конечно, не обязательно) и называть методы внутри компонентов с слов "handle", то есть будет `handleDeleteCard`. Это не обязательно, и о таком зачастую договариваются внутри команды.

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Card/Card.tsx
> +  onDelete: Function;
А зачем здесь такой тип? Лучше будет `(card: Card) => void` или `(cardId: string) => void`

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Card/Card.tsx
> +        />
Попробуй использовать библиотеку vite-plugin-svgr - это позволит использовать свг напрямую, и хранить их в формате свг. Так будет проще их поддерживать и добавлять.

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Card/Card.tsx
> +  return (
Вкусовщина, но перед return хорошо смотрится пустая строка :)

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  const [title, setTitle] = useState<string>('');
Можно не уточнять тип в случае, если по дефолтному значению можны вычислить типа днных.

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  const handleChangeTitle: React.FormEventHandler<Element> = (
Почему такой тип у этого метода?

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +    if (title !== '') setIsDisabled(false);
Лучше добавлять фигурные скобочки, иначе легко ошибиться

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  const handleChangeDescription: React.FormEventHandler<Element> = (
Почему такой тип у этого метода?

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  const onSubmit: React.FormEventHandler<Element> = (e: React.FormEvent) => {
Почему `onSubmit`, а не `handleSubmit`? Почему событие не форме самой, а на кнопке?

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +      <Button disabled={isDisabled} children={'Add card'} onClick={onSubmit} />
Почему `children` так назначен?

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  onAddCard: Function;
Это не очень хороший тип, лучше прописать конкрентее, например `onAddCard: (card: Task) => void`

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +    onAddCard(newCards);
Почему эта логика здесь, а не просто возвращение новой карты?

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  closeModal: Function;
Почему не `onCloseModal`?

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  className?: string;
Зачем здесь `className`, если он не используется?

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Modal/Modal.tsx
> +  className?: string;
Зачем здесь className?

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Modal/Modal.tsx
> +  closeModal: React.MouseEventHandler;
Почему не `onCloseModal`?

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/ts/classes/simpleCard/simpleCard.ts
> +export default class simpleCard implements Card {
Зачем делать это в виде класса?

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/TodoList/TodoList.tsx
> +    );
Не очень понимаю, а зачем здесь эта логика? Может проще при назначении дефолтных значений для `cards` это сделать?

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/TodoList/TodoList.tsx
> +              key={index}
А почему бы не использовать id?

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/TodoList/TodoList.tsx
> +        {cards.map((item, index) => {
Почему не назвать `card`, а не `item`?

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Card/Card.tsx
> +  card: Task;
Зачем передевать `title`, `description` и `card`, откуда эти значения и берутся?

2024-05-10 21:52 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/TodoList/TodoList.tsx
> +  };
Можно назвать handle...

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/TodoList/TodoList.tsx
> +  };
Переименовала

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/Card/Card.tsx
> +  card: Task;
title, description  из объектов массива с данными, card это один элемент массива, получаемый при использовании .map()

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/TodoList/TodoList.tsx
> +        {cards.map((item, index) => {
Поменяла

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/TodoList/TodoList.tsx
> +              key={index}
Cтроковые id не нравятся, как ключи реакту
![image](https://github.com/Tauders/dratuIT/assets/87136385/976133bc-c2e9-4572-a360-84800732f863)
Но согласна, что индексы не безопасны, оставила только цифры для ключа

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/TodoList/TodoList.tsx
> +    );
Эта логика нужна, так как мне надо искусственно созданные данные еще подгружать, и сортировать их

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/ts/classes/simpleCard/simpleCard.ts
> +export default class simpleCard implements Card {
Чтобы потом легче было расширять?

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/Modal/Modal.tsx
> +  closeModal: React.MouseEventHandler;
Поправила

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/Modal/Modal.tsx
> +  className?: string;
Ответила в другом комментарии

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  className?: string;
Условно, компонент, может быть в дальнейшем и переиспользован, и тогда дополнительный класс может пригодиться, поправила, но такой логикой руководствовалась

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  closeModal: Function;
Поправила

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +    onAddCard(newCards);
Поправила

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  onAddCard: Function;
Поправила

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +      <Button disabled={isDisabled} children={'Add card'} onClick={onSubmit} />
Поправила

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  const onSubmit: React.FormEventHandler<Element> = (e: React.FormEvent) => {
Поправила

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  const handleChangeDescription: React.FormEventHandler<Element> = (
Поправила

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +    if (title !== '') setIsDisabled(false);
Добавила

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  const handleChangeTitle: React.FormEventHandler<Element> = (
Уже поняла, по похожему комментарию, что это не подходит сюда

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  const [title, setTitle] = useState<string>('');
Без типа ругается

2024-05-11 12:43 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/Card/Card.tsx
> +  return (
Добавила пустую строку

2024-05-11 12:44 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/Card/Card.tsx
> +        />
Поменяла на библиотеку

2024-05-11 12:44 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/Card/Card.tsx
> +  onDelete: Function;
Поправила.

2024-05-11 12:44 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/Card/Card.tsx
> +  const deleteCard: React.MouseEventHandler = () => {
Поправила.

2024-05-11 12:44 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/Button/Button.tsx
> +    ? className + ' ' + classes.button
Использовала библиотеку

2024-05-11 12:44 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/Button/Button.tsx
> +  onKeyDown?: React.FormEventHandler<Element>;
FormEventHandler нужен был бы если бы использовала отдельно onSubmit в форме, но раз через onClick это делаю, тогда не нужен, предполагаю.
Указала конкретный элемент.

2024-05-11 12:44 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/Button/Button.tsx
> +  disabled,
Сделала, как лучше)

2024-05-11 12:44 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/Button/Button.tsx
> +    : classes.button;
Использовала библиотеку

2024-05-11 12:44 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/.prettierrc.json
> +}
Добавила строку

2024-05-11 14:01 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  className?: string;
Есть такой хороший метод YAGNI, буквально "тебе это не понадобится". (You aren't gonna need it). Смысл такой, что если тебе сейчас это не надо, но, в будущем, возможно, понадобится, то в будущем и можно будет добавить. Если что-то не используется здесь и сейчас, нужно ли оно здесь и сейчас? 
Расширяемость компонентов (потенциальная) хорошо, но это требует дополнительной поддержки и дополнительной работы с кодом, что влечёт дополнительные усилия, которые в данный момент не особо нужны.

2024-05-11 14:03 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/ts/classes/simpleCard/simpleCard.ts
> +export default class simpleCard implements Card {
А как это упростит дальнейшее расширение? Ты планируешь использовать это не просто для передачи данных, а для чего-то ещё? На текущий момент всё, что угодно, что имеет интерфейс `Card` тебе подходит (особенности типизации ТС), так зачем делать класс, который содержит в себе только поля, и который будет не сильно полезен без методов и тд?

2024-05-11 14:04 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/TodoList/TodoList.tsx
> +    );
Извини, не понимаю, какие искусственно созданные данные? Почему, когда ты назначаешь дефолтное значение в useState, это не подходит?

2024-05-11 14:05 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/TodoList/TodoList.tsx
> +              key={index}
А у тебя все элементы имеют реально валидный id? В том плане, что строка то реакту нормально должна подходить, по типизации. Судя по типам
```
type Key = string | number | bigint;
```

2024-05-11 14:08 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/TodoList/TodoList.tsx
> +    );
Грубо говоря, почему бы не сделать так?
```
  const [cards, setCards] = useState<Task[]>(
    dataTasks
      .map((task, index) => {
        task.id = uuidv4();
        task.order = index + 1;
        return task;
      })
      .sort(sortByCardOrder)
  );
```
?

2024-05-11 14:09 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/TodoList/TodoList.tsx
> +              key={index}
Я понял, почему. У тебя при первом рендере нет `id` ещё, если поменяешь, чтобы useState дефолтные значения сразу ставил с id, такая проблема пропадёт, так как id будет всегда.

2024-05-11 14:11 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Card/Card.tsx
> +  card: Task;
Не понимаю, у тебя есть такое использование.
```ts
              key={card.id}
              title={card.title}
              description={card.description}
              onDelete={handleDeleteCard}
              card={card}
```
Ты передаёшь card и данные же из него.
Почему бы не передавать только card и не рендерить внутри теже данные?
```ts
type CardProps = {
  card: Task;
  onDelete: (card: Task) => void;
};

export const Card = ({ card, onDelete }: CardProps) => {
  const handleDeleteCard: React.MouseEventHandler = () => {
    onDelete(card);
  };

  return (
    <li className={classes.card}>
      <h3 className={classes.card__title}>{card.title}</h3>
      <p className={classes.card__description}>{card.description}</p>
      <Button className={classes.card__button_light} onClick={handleDeleteCard}>
        <DeleteIcon
          width={16}
          height={16}
          className={classes.card__icon}
          preserveAspectRatio="xMidYMid meet"
          color="#7c4886"
        />
      </Button>
    </li>
  );
};
```
и оставить 
```ts
            <Card
              key={card.id}
              onDelete={handleDeleteCard}
              card={card}
            />
```

2024-05-11 14:12 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  const [title, setTitle] = useState<string>('');
А на каком этапе? Если я так делаю
```ts
  const [title, setTitle] = useState('');
```
у меня не ругается, так как есть дефолтное значение, из которого ТС может вычислить тип однозначно.

2024-05-11 14:13 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Button/Button.tsx
> +  disabled,
Здесь вкусовщина, а не совсем "однозначно лучше", так что может и не точно :)

2024-05-11 14:30 UTC, Tauders requested changes

2024-05-11 14:30 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Button/Button.tsx
>  }: ButtonProps) => {
Опять же, здесь вкусовщина, но есть другой способ так разбивать. 
```ts
export const Button = (props: ButtonProps) => {
  const { className, onClick, onKeyDown, children, isDisabled } = props;

  return (
    <button
      className={classNames(className && className, classes.button)}
      onClick={onClick}
      onKeyDown={onKeyDown}
      disabled={isDisabled}
    >
      {children}
    </button>
  );
};
```
Мне, лично, (оставляю на твой вкус), такое нравится больше.

2024-05-11 14:30 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Button/Button.tsx
> +      className={classNames(className && className, classes.button)}
Можно по-другому использовать библиотеку, будет чуть понятнее выглядеть:
```ts
className={classNames(classes.button, { className: className })}
```
или даже так:
```ts
className={classNames(classes.button, { className: Boolean(className) })}
```

2024-05-11 14:30 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Card/Card.tsx
> +          preserveAspectRatio="xMidYMid meet"
Оно так и должно выглядеть?
![image](https://github.com/Tauders/dratuIT/assets/4114636/77a4e4a0-4ed7-4276-96ab-250b868a2846)
Там и должен быть цвет фона поменян, а не цвет линий?

2024-05-11 14:30 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Card/Card.tsx
> +          preserveAspectRatio="xMidYMid meet"
Нужен ли аттрибут `preserveAspectRatio`? Может его лучше в саму svg переместить? Можно ли размер указать через класс?

2024-05-11 14:30 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  onAddCard: (cards: Task) => void;
Почему название `cards`, если это одна таска? Почему вообще `cards`, а не `task`?

2024-05-11 14:30 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> -    if (title !== '') setIsDisabled(false);
Ты интересно поправила багу, но ты прочитала, почему бага возникала? Можешь объяснить?

2024-05-11 14:30 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  const handleChangeTitle: React.ChangeEventHandler<HTMLInputElement> = (
Вкусовщина, но можно убрать возвращаемый тип

2024-05-11 14:30 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
>      const prevCard: Task = cards[cards.length - 1];
Если мы подразумеваем некое переиспользование (что мы должны делать, в целом), может лучше возвращать без `order`, вычисленного здесь, а вычислять его в родительском компоненте? Так не надо будет передавать сюда все карточки, и сама форма добавления не будет контролировать то, в каком порядке что добавляется.

2024-05-11 14:30 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Modal/Modal.tsx
> +  onCloseModal: React.MouseEventHandler;
Вкусовщина, но важно ли нам, что это именно мышкой кликнутый ивент? В плане, а что если там будет ещё клик на клавиатуру? Не лучше ли будет сделать более общий вариант, типа `() => void`?

2024-05-11 14:30 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Modal/Modal.tsx
>                color="#7c4886"
Так же, как для кнопки Delete

2024-05-11 14:30 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/TodoList/TodoList.tsx
> +          className={classes.todoListSection__icon}
Так же, как для delete,

2024-05-11 14:35 UTC, Tauders requested changes

2024-05-11 14:35 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +      />
Может стоит заиспользовать дефолтные валидации от html для форм? Тогда кнопка всегда будет активна, но, пока пользователь не введёт данные, он не сможет отправить их. Так можно убрать useEffect.

2024-05-11 16:17 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  const [title, setTitle] = useState<string>('');
Хм, возможно, я что-то тыкнула случайно, сейчас все ок

2024-05-11 16:17 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  className?: string;
Хорошо

2024-05-11 16:17 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/ts/classes/simpleCard/simpleCard.ts
> +export default class simpleCard implements Card {
Убрала

2024-05-11 16:17 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/TodoList/TodoList.tsx
> +              key={index}
Поправила

2024-05-11 16:18 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/Card/Card.tsx
> +  card: Task;
Поправила

2024-05-11 16:18 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/Button/Button.tsx
>  }: ButtonProps) => {
Изменила

2024-05-11 16:18 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/Button/Button.tsx
> +      className={classNames(className && className, classes.button)}
На мой взгляд мой вариант понятнее, лично мне по крайней мере, если только в этом преимущество)
Может , что еще надо добавить, у меня оба твоих варианта не отрабатывают

2024-05-11 16:18 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/Card/Card.tsx
> +          preserveAspectRatio="xMidYMid meet"
У меня все ок - 
![image](https://github.com/Tauders/dratuIT/assets/87136385/f7dd9f7d-4518-4e85-8248-4b9f1fc7e19b)

Но если ты менял что-то с классами в кнопке, когда смотрел, могло из-за этого не отработать

2024-05-11 16:18 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/Card/Card.tsx
> +          preserveAspectRatio="xMidYMid meet"
Поместила в svg, указала размеры через класс

2024-05-11 16:18 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  onAddCard: (cards: Task) => void;
Забыла поправить, когда меняла после прошлых комментариев

2024-05-11 16:18 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> -    if (title !== '') setIsDisabled(false);
Ну потому что оно должно еще раз отрендериться, чтобы новое состояние установить, у него там еще старое на тот момент состояние, когда я проверку делаю

2024-05-11 16:18 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +  const handleChangeTitle: React.ChangeEventHandler<HTMLInputElement> = (
Убрала

2024-05-11 16:18 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
>      const prevCard: Task = cards[cards.length - 1];
Поправила

2024-05-11 16:18 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/Modal/Modal.tsx
> +  onCloseModal: React.MouseEventHandler;
Поменяла

2024-05-11 16:18 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/Modal/Modal.tsx
>                color="#7c4886"
Поправила

2024-05-11 16:18 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/TodoList/TodoList.tsx
> +          className={classes.todoListSection__icon}
Поправила

2024-05-11 16:18 UTC, VeronikaFront commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +      />
Поменяла

2024-05-11 23:17 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Button/Button.tsx
> +      className={classNames(className && className, classes.button)}
Окей, тогда можно и так оставить

2024-05-11 23:18 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> -    if (title !== '') setIsDisabled(false);
Да, это важно понимать, так как может вести к багам.

2024-05-11 23:23 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/TodoList/TodoList.tsx
> +      .sort(sortByCardOrder)
Если такое кажется не очень понятным и не очень хорошо смотрится, можно убрать это в подготовку данных. То есть сделать метод в в файле dataTasks, который будет это делать в файле.

2024-05-11 23:23 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/TodoList/TodoList.tsx
> +          order: cards.length > 0 && prevCard.order ? prevCard.order + 1 : 1,
Здесь это не так важно, так как индекс от 1, но в целом проверять числа вот так может привести к проблеме, если там валидное значение 0. Так как такое вычисление при 0 будет неверным. (условие не выполнится)

2024-05-11 23:23 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/Card/Card.tsx
> +          preserveAspectRatio="xMidYMid meet"
Да, я сам накосячил :)

2024-05-11 23:50 UTC, Tauders requested changes
Я бы ещё предложил подумать над организацией файлов, чтобы она была чуть проще для расширения дальнейшего.
Один из таких подходов, это делить всё на компоненты и страницы. Страницы это нечто, что можно отрендерить по финальному урлу.
Оно может выглядеть как-то так:
![image](https://github.com/Tauders/dratuIT/assets/4114636/47bb3561-dfee-4131-a393-d58b2eda3b8f)

2024-05-11 23:50 UTC, Tauders commented on ReactTasks/task-1/stage-2/src/components/FormAddingCard/FormAddingCard.tsx
> +    const newCard = {
Здесь бы в идеале указать тип как раз, чтобы проверка на данные была, типа 
```
const newTask: Task = {
...
```

2024-05-14 16:02 UTC, Tauders approved these changes

2024-05-14 16:03 UTC, merged