React tasks/task 1/stage 3
Tauders/denis-tasks pull request #46
Opened 2024-05-14 16:36 UTC by VeronikaFront

На данном этапе необходимо дополнить приложение с предыдущего этапа возможностью менять порядок задач в списке.

2024-05-15 08:22 UTC, Tauders requested changes

2024-05-15 08:22 UTC, Tauders commented on ReactTasks/task-1/stage-3/src/pages/TodoList/components/Card/Card.tsx
> +  handleDragOver: React.DragEventHandler;
Все ли эти ивенты нужны для пробрасывания драг-н-дропа? Почему они так называются? А не `on...` (onDrop)?

2024-05-15 08:22 UTC, Tauders commented on ReactTasks/task-1/stage-3/src/pages/TodoList/components/Card/Card.tsx
> +      draggable={true}
Мне так нравится самому больше, но, если что, указывать здесь `true` не обязательно, наличие самого пропса и так сделает его `true`.

2024-05-15 08:22 UTC, Tauders commented on ReactTasks/task-1/stage-3/src/pages/TodoList/TodoList.tsx
> +  const dropHandler = (e: React.DragEvent, task: Task) => {
А почему здесь такое название, а не просто handleDrop?

2024-05-15 15:46 UTC, VeronikaFront commented on ReactTasks/task-1/stage-3/src/pages/TodoList/components/Card/Card.tsx
> +  handleDragOver: React.DragEventHandler;
По идее  handleDragLeave не особо нужен, убрала
Переименовала, немного запуталась в названиях)

2024-05-15 15:46 UTC, VeronikaFront commented on ReactTasks/task-1/stage-3/src/pages/TodoList/TodoList.tsx
> +  const dropHandler = (e: React.DragEvent, task: Task) => {
Переименовала

2024-05-16 05:06 UTC, Tauders approved these changes

2024-05-16 06:35 UTC, merged