React tasks/task 1/stage 4
Tauders/denis-tasks pull request #47
Opened 2024-05-16 07:53 UTC by VeronikaFront

На данном этапе необходимо сделать, чтобы задачи сохранялись при перезагрузке странице и загружались при открытии. Это необходимо сделать без использования бэкэнда, с выбором технологий, доступных в браузере.

2024-05-17 12:24 UTC, Tauders requested changes

2024-05-17 12:24 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/pages/TodoList/TodoList.tsx
> +      cardsJson !== null ? JSON.parse(cardsJson) : null;
Здесь бы, по хорошему, проверить, соответствует ли тип `Task[]` и то, что хранится внутри строки. Для этого можно использовать type guard'ы
https://www.typescriptlang.org/docs/handbook/advanced-types.html

2024-05-17 12:24 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/pages/TodoList/TodoList.tsx
> +    }
Мне кажется, что не стоит это делать всегда безусловно, стоит или добавить аргумент, типа "включать дефолтные таски", или вообще убрать отсюда и делать в момент вызова.
Какая мотивация у такого коммента? Если ты будешь использовать эту функцию, то, скорее всего, ты будешь ориентироваться на её название, и тут ты получаешь что-то вообще непонятное. Типа почему там какие-то странные значения, если у меня нет ничего в локалсторадже.

2024-05-17 12:24 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/pages/TodoList/TodoList.tsx
> +    const cardsJson = localStorage.getItem('cards');
Не обязательно, но, по-хорошему, вынести бы `cards` в константу, так как ты их внизу устанавливаешь, и может быть рассинхрон, если переименуешь.

2024-05-17 12:24 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/pages/TodoList/TodoList.tsx
> +  const getItemsInStorage = () => {
А зачем это внутри компонента? Не лучше ли вынести в отдельный файл, или объединить с сохранением в локал стораге и вынести оба метод в что-то отдельное.

2024-05-17 12:24 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/pages/TodoList/TodoList.tsx
> +  const getItemsInStorage = () => {
Кажется `getItemsFromStorage` будет лучше. Или даже `getItemsFromLocalStorage` (так как существует, например, sessionStorage)

2024-05-17 12:24 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/pages/TodoList/TodoList.tsx
> +  const getItemsInStorage = () => {
Посмотри на сигнатуру самого локалстораджа, и как они обрабатывают "дефолтные значения"

2024-05-17 12:24 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/pages/TodoList/TodoList.tsx
> +    localStorage.setItem('cards', JSON.stringify(newCards));
Здесь localStorage хороший выбор, как ещё можно было бы сделать? В чём была бы разница? (есть несколько способов, которые "на поверхности". Если интересно, то попробуй распиши, может быть в будущем полезно.

2024-05-17 12:24 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/pages/TodoList/TodoList.tsx
> +      setItemInStorage(newCards);
А может здесь будет проще использовать эффект?

2024-05-17 15:24 UTC, VeronikaFront commented on ReactTasks/task-1/stage-4/src/pages/TodoList/TodoList.tsx
> +      cardsJson !== null ? JSON.parse(cardsJson) : null;
Добавила проверку, но я не до конца уверена, что надо было именно так, я долго с этим мучилась, ничего лучше не придумала

2024-05-17 15:25 UTC, VeronikaFront commented on ReactTasks/task-1/stage-4/src/pages/TodoList/TodoList.tsx
> +    }
Убрала в состояние

2024-05-17 15:25 UTC, VeronikaFront commented on ReactTasks/task-1/stage-4/src/pages/TodoList/TodoList.tsx
> +    const cardsJson = localStorage.getItem('cards');
Вынесла в константу

2024-05-17 15:25 UTC, VeronikaFront commented on ReactTasks/task-1/stage-4/src/pages/TodoList/TodoList.tsx
> +  const getItemsInStorage = () => {
Убрала в отдельный файл

2024-05-17 15:26 UTC, VeronikaFront commented on ReactTasks/task-1/stage-4/src/pages/TodoList/TodoList.tsx
> +  const getItemsInStorage = () => {
Переименовала

2024-05-17 15:26 UTC, seal-developer commented on ReactTasks/task-1/stage-4/src/pages/TodoList/TodoList.tsx
> +      setItemInStorage(newCards);
Поменяла на useEffect

2024-05-17 15:29 UTC, Tauders requested changes

2024-05-17 15:29 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/data/dataTasks.ts
> +export const isTask = (task: any): task is Task => {
Здесь лучше бы не any, а `unknown`, и проверять, что за тип изначально у task. На текущий момент, если task вообще не определён, то у тебя будут проблемы с проверкой.

2024-05-17 15:29 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/ts/operateLocalStorage.ts
> +  const cards: Task[] = JSON.parse(cardsJson);
А не проще ли проверять тип сразу на массив?

2024-05-17 15:29 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/ts/operateLocalStorage.ts
> +    if (!isType(card)) {
Зачем передевать, как функцию, а не использовать напрямую?

2024-05-17 15:30 UTC, VeronikaFront commented on ReactTasks/task-1/stage-4/src/pages/TodoList/TodoList.tsx
> +    localStorage.setItem('cards', JSON.stringify(newCards));
Ну еще есть IndexedDB, но мне кажется для такой маленькой задачи слишком избыточно. Есть несколько типов ключей, больше данных можно хранить, из основного.
Честно говоря, я не знаю больше хороших способов для хранения подобных данных именно в браузере)
Куки не подходят сюда, а что еще есть?

2024-05-17 15:45 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/pages/TodoList/TodoList.tsx
> +    localStorage.setItem('cards', JSON.stringify(newCards));
ИндексидДБ, как ты правильно указала.
Сесион стораге, но у него сильно ограниченее срок жизни.
Почему в куках нельзя?
Ещё можно дб в браузер другую захерачить, но это уже сложнее и не нужнее.

2024-05-17 16:04 UTC, VeronikaFront commented on ReactTasks/task-1/stage-4/src/pages/TodoList/TodoList.tsx
> +    localStorage.setItem('cards', JSON.stringify(newCards));
Мне кажется, для такой задачи с куки будет слишком много мороки, и проще localStorage  использовать, он удобнее, и больше вмещает, куки же больше для передачи конфиденциальной информации подходят насколько я знаю, здесь это не надо
Ну сессия это понятно, но тоже не особо сюда идет, как мне кажется, обидно, когда сделал список задач, закрыл браузер и все исчезло))
"Ещё можно дб в браузер другую захерачить, но это уже сложнее и не нужнее" - такое я не умею)

2024-05-17 16:12 UTC, Tauders requested changes

2024-05-17 16:12 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/ts/operateLocalStorage.ts
> +    JSON.parse(cardsJson).length <= 0
Зачем ты парсишь 2 раза один и тот же набор данных?

2024-05-17 16:12 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/ts/operateLocalStorage.ts
> +    ) {
Лучше всё же это вынести в отдельный type guard, который принимает на вход тип данных unknown, но который бы возвращал, является ли проверяемый тип `Task[]`.

2024-05-17 18:00 UTC, Tauders requested changes

2024-05-17 18:00 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/ts/operateLocalStorage.ts
> +    if (!isTask(card)) {
Здесь это может не настолько важно, но попробуй чисто для практики. Сделай тайпгард, который будет проверять не isTask, а isTasks (или там должно быть areTasks). Чтобы возвращал тайпгард то, что аргумент типа unknown является типом `Task[].

2024-05-17 18:00 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/ts/operateLocalStorage.ts
> +  const cards: Task[] = JSON.parse(cardsJson);
Здесь всё ещё 2ой раза парсишь

2024-05-17 18:32 UTC, VeronikaFront commented on ReactTasks/task-1/stage-4/src/ts/operateLocalStorage.ts
> +  const cards: Task[] = JSON.parse(cardsJson);
Увидела, но в целом убрала в общую проверку типов - проверки на массив и длину массива, чтобы не дублировать

2024-05-18 03:49 UTC, Tauders requested changes

2024-05-18 03:49 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/data/dataTasks.ts
> +    }
Кажется это всё же было бы лучше убрать в отдельную функцию, так как это позволит и метод упростить, и переиспользовать, если надо будет 1 таск затайпгардить.

2024-05-18 03:49 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/data/dataTasks.ts
> +  if (!(tasks instanceof Array) || tasks.length === 0) {
Лучше проверять через `Array.isArray` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#instanceof_vs._array.isarray 
Здесь это не так важно, но в целом лучше использовать его.

Почему пустой массив не подходит?

2024-05-18 03:49 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/ts/operateLocalStorage.ts
>  const localStorageCardsKey: string = 'cards';
Здесь можно не указывать тип

2024-05-18 03:49 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/ts/operateLocalStorage.ts
>    const cardsJson: string | null = localStorage.getItem(localStorageCardsKey);
Здесь можно не указывать тип

2024-05-18 03:49 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/ts/operateLocalStorage.ts
>    const cards: Task[] = JSON.parse(cardsJson);
А здесь лучше убрать тип вообще, так как это не совсем честное приведение типов, а внизу ты как раз это проверяешь (соответствует ли типу)

2024-05-18 03:49 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/ts/operateLocalStorage.ts
>      return false;
Иметь настолько разные выходы (типа `false | Task[]`) допустимо, но не очень желательно, так как не понятно, когда и что вернётся.
Здесь лучше добавить агрумент функции с дефолтным значением, и возвращать его.
```ts
export const getItemsFromLocalStorage = (defaultValues: Task[] = []) => {
  const cardsJson = localStorage.getItem(localStorageCardsKey);

  if (cardsJson === null) {
    return defaultValues;
  }
...
```
Или возвращать `undefined` или `null` (что похоже на boolean, но несёт немного более понятный смысл, типа "там ничего нет").

2024-05-18 13:32 UTC, Tauders requested changes

2024-05-18 13:32 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/data/dataTasks.ts
> +    typeof task.order === 'number' &&
А эти поля же не обязательны в типе, так что проверка не совсем правильная, если этих полей даже нет, то это всё ещё Task

2024-05-18 14:27 UTC, Tauders approved these changes, later dismissed

2024-05-18 14:27 UTC, Tauders commented on ReactTasks/task-1/stage-4/src/data/dataTasks.ts
> +    return false;
Здесь else не обязателен

2024-05-18 15:17 UTC, Tauders approved these changes

2024-05-18 15:17 UTC, merged