[task 1, stage 5]
Tauders/denis-tasks pull request #48
Opened 2024-05-19 13:56 UTC by VeronikaFront

На данном этапе необходимо добавить поддержку нескольких списков задач, с возможностью задавать название каждому списку.

2024-05-30 15:02 UTC, Tauders requested changes

2024-05-30 15:02 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/components/Form/Form.tsx
> +  textBtn: string;
Зачем сокращать `textButton` до `textBtn`?

2024-05-30 15:02 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/pages/TodoList/TodoList.module.scss
> +}
Пустая строка.

2024-05-30 15:02 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/hooks/useModal.ts
> +  }, [isOpen]);
А зачем зависимость от isOpen?

2024-05-30 15:02 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/hooks/useModal.ts
> +  const handleOpenModal = useCallback(() => {
А зачем здесь useCallback? (это не плохо, мне просто интересно твоё понимание)

2024-05-30 15:02 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/hooks/useForm.ts
> +  const onChangeTitle = (e: React.ChangeEvent<HTMLInputElement>) =>
Почему здесь `on...`, а внизу `handle...`?

2024-05-30 15:02 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/hooks/useForm.ts
> +  const [state, dispatch] = useReducer(reducer, initState);
А не проще ли здесь использовать 2 useState? Выбор за тобой, мне просто интересно :)

2024-05-30 15:02 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/hooks/useForm.ts
> +};
Почему с маленькой буквы?

2024-05-30 15:02 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/hooks/useForm.ts
> +const enum reducerAction {
Здесь не критично, но лучше почитать, что использовать enum надо аккуратно в TS

2024-05-30 15:02 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/pages/TodoList/TodoList.tsx
> +  const defaultLists = [
Желательно указать тип данных, и можно вынести за пределы компонента, чтобы не рендерилось каждый раз

2024-05-30 15:02 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/pages/TodoList/components/FormAddingCard/FormAddingCard.tsx
> +    if (!isString(description)) {
Немного не понял, а зачем здесь эта проверка? Здесь может быть что-то, кроме строки?

2024-05-30 15:02 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/pages/TodoList/components/FormAddingList/FormAddingList.tsx
> +  const { title } = state;
А надо ли здесь использовать этот хук, если здесь только тайтл?

2024-05-30 15:02 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/pages/TodoList/components/List/List.tsx
> +  onList: (id: string, title: string, cards: Task[]) => void;
Что значит `onList`?

2024-05-30 15:02 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/pages/TodoList/components/List/List.tsx
> +  const [currentCard, setCurrentCard] = useState<null | Task>(null);
Здесь это не важно, но почему `null`, а не `undefined`?

2024-05-30 15:02 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/pages/TodoList/components/List/List.tsx
> +export type List = {
А стоит ли хранить тип, который используется много где, в рамках этого компонента?

2024-05-30 15:02 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/ts/isType.ts
> +export const isString = (prop: unknown): prop is string => {
А нужна ли такая проверка вообще?

2024-05-30 15:02 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/ts/isType.ts
> +  return false;
А может лучше тернарную проверку?

2024-05-30 15:02 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/components/Modal/Modal.tsx
> +          <Button
Здесь это не так важно, но в целом лучше `type="button"` писать, а то может привести к проблемам, когда форма будет содержать кнопку, которая отправляет данные, но не должна.

2024-05-30 15:02 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/components/Form/Form.tsx
> +  return (
Почему иногда перед return нет пробела, а иногда есть?

2024-05-31 11:45 UTC, seal-developer commented on ReactTasks/task-1/stage-5/src/hooks/useModal.ts
> +  const handleOpenModal = useCallback(() => {
Я прочитала, что функции в кастомных хуках всегда стоит оборачивать в useCallback во избежании лишних перерендеров, хотя здесь он не на что не влияет

2024-05-31 11:47 UTC, seal-developer commented on ReactTasks/task-1/stage-5/src/hooks/useForm.ts
> +  const onChangeTitle = (e: React.ChangeEvent<HTMLInputElement>) =>
Не поняла, где внизу

2024-05-31 11:49 UTC, seal-developer commented on ReactTasks/task-1/stage-5/src/hooks/useForm.ts
> +  const [state, dispatch] = useReducer(reducer, initState);
А я знаю, что это избыточно здесь, у меня была другая реализация в прошлом коммите, мне просто хотелось попробовать

2024-05-31 11:54 UTC, seal-developer commented on ReactTasks/task-1/stage-5/src/pages/TodoList/components/FormAddingCard/FormAddingCard.tsx
> +    if (!isString(description)) {
Не может, но ts ругается
![image](https://github.com/Tauders/dratuIT/assets/87136385/15d41946-8824-4d9a-865b-4b053e250d45)

2024-05-31 12:04 UTC, seal-developer commented on ReactTasks/task-1/stage-5/src/pages/TodoList/components/FormAddingCard/FormAddingCard.tsx
> +    if (!isString(description)) {
Я убрала, так как поменяла реализацию, и сейчас не актуально, но в целом не стоило так делать, чтобы к этому привело

2024-06-03 17:42 UTC, Tauders requested changes

2024-06-03 17:42 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/components/Button/Button.tsx
> +  type: 'button' | 'submit' | 'reset';
Можно взять из HTMLButtonElement

2024-06-03 17:42 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/components/Button/Button.tsx
> +type ButtonProps = {
Кстати, можно взять в целом часть пропсов из HTMLButtonElement, или даже все, кроме уникальных, нужных тебе

2024-06-03 17:42 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/pages/TodoList/TodoList.tsx
> +export type ListType = {
`ListType` не очень хорошее название, лучше делать ближе к теме, например `ListOfTasks` или `TodoList`. И почему он определён в этом файле, если он используется в других файлах? Лучше вынести в более общее место.

2024-06-03 17:42 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/pages/TodoList/components/Card/Card.tsx
> +      draggable={true}
А почему ты иногда пишешь `={true}`, а иногда не пишешь для булевых пропсов?

2024-06-03 17:42 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/pages/TodoList/components/List/List.tsx
> +export const List = (props: ListProps) => {
А почему есть `List` и `TodoList`?

2024-06-03 17:42 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/ts/isType.ts
> +};
Пустая строка

2024-06-16 07:57 UTC, Tauders approved these changes, later dismissed

2024-06-16 07:57 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/pages/TodoLists/TodoLists.tsx
> +
Зачем 3 пустые строки?

2024-06-16 07:57 UTC, Tauders commented on ReactTasks/task-1/stage-5/src/ts/utils.ts
> +import { Task } from "./types";
А почему 2ая кавычка?

2024-06-18 06:31 UTC, Tauders approved these changes

2024-06-18 06:33 UTC, merged