Написал код программы сумматора
Tauders/denis-tasks pull request #6
Opened 2021-05-12 08:06 UTC by St1ke

1)Ввёл две переменные типа double, 
2)Дальше сделал так чтоб выводилось сообщение в консоли о том что нужно сделать, 3)Конвертировал обе переменных чтоб консоль могла считывать вводимые значения, 
4)Ввёл третью переменную которая обозначает сумму вводимых чисел
5)Написал код для вывода результата суммы в консоли

2021-05-12 08:13 UTC, Tauders requested changes

2021-05-12 08:13 UTC, Tauders commented on task-2/Summator/Summator/Program.cs
> +            Console.WriteLine("Cумма " + a + " и " + b + " равна " + total + ".");
Используй интерполяцию строк.

2021-05-12 08:40 UTC, Tauders requested changes
Надо добавить обработку исключений

2021-05-12 09:17 UTC, CodingFeles requested changes

2021-05-12 09:17 UTC, CodingFeles commented on task-2/Summator/Summator/Program.cs
> +            b = Convert.ToDouble(Console.ReadLine());
Про обработку исключений: здесь у тебя Console.ReadLine считывает строку, которую ввёл пользователь. Convert.ToDouble пытается превратить переданную ему строку в double. Что произойдёт если передать строку, которая не задержит числовых значений? Например: "abc" ?

2021-05-13 06:34 UTC, Tauders requested changes

2021-05-13 06:34 UTC, Tauders commented on task-2/Summator/Summator/Program.cs
> +
Лишняя пустая строка

2021-05-13 06:34 UTC, Tauders commented on task-2/Summator/Summator/Program.cs
> +                Console.WriteLine("Введите числовые значения.");
Здесь лучше писать, что было сделано не так - т.е., например, "Введены некоректные значения, пожалуйста, введите числа и попробуйте ещё раз".
В конкретно этом случае нормально и так, просто на будущее.

2021-05-13 06:34 UTC, Tauders commented on task-2/Summator/Summator/Program.cs
> +            }
В текущем виде не нужен, т.к. что будет, если пользователь здесь введёт неправильные значения? Если хочешь, можешь использовать цикл бесконечный, чтобы пользователь мог вводить много раз, но в рамках задачи не требуется.

2021-05-13 06:37 UTC, CodingFeles requested changes

2021-05-13 06:37 UTC, CodingFeles commented on task-2/Summator/Summator/Program.cs
> +            catch
Я не уверен, что стоит писать catch без каких-либо уточнений. Документация не рекомендует так делать. Однако, в данном случае не знаю - пусть Вова оценит.

2021-05-13 06:37 UTC, CodingFeles commented on task-2/Summator/Summator/Program.cs
> +            finally
Блок finally нужен для вещей, который должны произойти независимо от того было брошено исключение в блоке try или нет.

А что будет, если тебе снова введут "abc"?
Тут два выхода:

1. Если ты хочешь дать возможность пользователю исправить свою ошибку и ввести что-то заного, то надо думать о том, как переделать программу, чтобы за один её запуск можно было проводить несколько сложений: тогда у тебя в случае исключения будет простой переход на следующую попытку сложения.
2. Если программа, как изначально была написана, предполагает только одну попытку сложить, то должна ли она заного предлагать пользователю исправиться? Или просто сообщить об ошибке и завершить свою работу.

2021-05-13 06:37 UTC, CodingFeles commented on task-2/Summator/Summator/Program.cs
> +                Console.WriteLine($"Сумма {a} и {b} равна {total}.");
Если ты хочешь вызывать один и тот же блок кода несколько раз - не копируй его. Для этого можно вынести код в отдельную функцию и уже её вызывать несколь раз.

2021-05-13 06:42 UTC, St1ke commented on task-2/Summator/Summator/Program.cs
> +                Console.WriteLine($"Сумма {a} и {b} равна {total}.");
> Если ты хочешь вызывать один и тот же блок кода несколько раз - не копируй его. Для этого можно вынести код в отдельную функцию и уже её вызывать несколь раз.

Да я знаю что циклами можно сделать всё красиво, как дойдем сделаю, хз просто решил сделать

2021-05-13 06:46 UTC, Tauders commented on task-2/Summator/Summator/Program.cs
> +            catch
Так делают, когда надо просто заглушить вообще все исключения, не сильно хорошая практика, и надо что-то делать с объектом исключения.

Давай сразу тогда и применим хорошую практику.

@St1ke добавь сюда код для получения исключения и выведи текст исключения на экран, когда говоришь пользователю, что он ввёл что-то не то.

Например:
```
Введены некоректные значения, пожалуйста, введите числа и попробуйте ещё раз. Полученная ошибка:
{Текст ошибки}
```

Текст ошибки на следующей строке

2021-05-13 07:21 UTC, CodingFeles commented on task-2/Summator/Summator/Program.cs
> +                Console.WriteLine($"Сумма {a} и {b} равна {total}.");
Нет, про циклы - это не сюда. Здесь о том, что если в нескольких местах нужен один и тот же код, то скорее всего этот код надо вынести в отдельную функцию.

2021-05-13 07:22 UTC, CodingFeles commented on task-2/Summator/Summator/Program.cs
> +                Console.WriteLine($"Сумма {a} и {b} равна {total}.");
Про циклы: это несколькими комментариями выше, где обсуждения про то как реагировать на ошибку.

2021-05-13 07:22 UTC, CodingFeles commented on task-2/Summator/Summator/Program.cs
> +            finally
Кстати, а ты заметил, что даже если ввёл правильные числа, то у тебя программа снова запросит числовые значения?

2021-05-13 07:53 UTC, St1ke commented on task-2/Summator/Summator/Program.cs
> +            catch
Не сразу понял о чем речь, тк в той главе которую @Tauders сказал прочитать для решения задачи ничего не было, но              когда изучал вопрос с помощью гугла натыкался на что то подобное, это типы исключений, я добавлю это, там вроде просто несколько категорий ошибок как я понял, но это нам не задавали), на метаните посмотрел, через одну главу как раз про типы есть.

2021-05-13 07:58 UTC, CodingFeles commented on task-2/Summator/Summator/Program.cs
> +            catch
Да, всё верно. По хорошему, catch должен "знать" какие типы исключений ловить, т.к. некоторые вещи лучше оставлять на откуп окружению.
"Нам не задавали" - к тебе никаких претензий нет. Ревью всегда будет критиковать работу по оформлению или существу, но в этом и смысл. Мы можем указывать на некоторые нюансы, даже если мы их не поясняли или они вне изучаемых тем. Если не получается самостоятельно разобраться или не очень понятно что делать - не стесняйся и обращайся к нам. Никаких негативных оценок тут нет.

2021-05-13 08:02 UTC, St1ke commented on task-2/Summator/Summator/Program.cs
> +                Console.WriteLine($"Сумма {a} и {b} равна {total}.");
> Если ты хочешь вызывать один и тот же блок кода несколько раз - не копируй его. Для этого можно вынести код в отдельную функцию и уже её вызывать несколь раз.

я понял кажется о чем речь, или в джаве сталкивался или как в математике, что куча действия обозначаются чем то одним и коротким, но я в общем так не умею пока судя по всему, поэтому просто уберу самодеятельность

2021-05-13 08:05 UTC, CodingFeles commented on task-2/Summator/Summator/Program.cs
> +                Console.WriteLine($"Сумма {a} и {b} равна {total}.");
Да, вкратце функции это именованные блоки кода, у которых описаны данные которые они получают и какие возвращают. А ты можешь по имени вызывать их из других блоков кода.

Самодеятельность - это хорошо. Мы просто будем давать советы, как её сделать лучше.
Но в данном случае блок finally тут просто не нужен.

2021-05-13 08:24 UTC, St1ke commented on task-2/Summator/Summator/Program.cs
> +            catch
> Да, всё верно. По хорошему, catch должен "знать" какие типы исключений ловить, т.к. некоторые вещи лучше оставлять на откуп окружению.
> "Нам не задавали" - к тебе никаких претензий нет. Ревью всегда будет критиковать работу по оформлению или существу, но в этом и смысл. Мы можем указывать на некоторые нюансы, даже если мы их не поясняли или они вне изучаемых тем. Если не получается самостоятельно разобраться или не очень понятно что делать - не стесняйся и обращайся к нам. Никаких негативных оценок тут нет.

Да просто пояснил в **рамках обучения** почему не знал, и понимаю почему и для чего делается.

2021-05-13 08:56 UTC, Tauders commented on task-2/Summator/Summator/Program.cs
> +            catch
@St1ke выведите текст ошибки ещё в консоль

2021-05-13 09:25 UTC, CodingFeles requested changes
Исправил большую часть как надо. Осталось немножко дожать обработку исключений.

2021-05-13 09:25 UTC, CodingFeles commented on task-2/Summator/Summator/Program.cs
> +            }
А ты проверял работает ли оно? Я не уверен, но сомневаюсь, что оно соберётся.

Просто FormatException - это тип. А интерполяция строк всё же ждёт, что ты будешь передавать какие-то значения или переменные.

Можно написать `catch (FormatException e)` и переменную `e` использовать в интерполяции. У исключений есть свойство Message, которое позволяет получить текст ошибки. Т.е. использовать надо `e.Message`.

2021-05-13 09:25 UTC, CodingFeles commented on task-2/Summator/Summator/Program.cs
> +            catch (FormatException)
А хватит ли нам только FormatException? @Tauders ? Я бы просто базовый Exception использовал.

2021-05-13 09:26 UTC, Tauders commented on task-2/Summator/Summator/Program.cs
> +            catch (FormatException)
Я бы тоже базовый использовал

2021-05-13 16:54 UTC, Tauders approved these changes

2021-05-13 17:30 UTC, CodingFeles approved these changes

2021-05-13 17:30 UTC, merged