Создан калькулятор-1
Tauders/denis-tasks pull request #9
Opened 2021-05-12 14:54 UTC by RatatataBoom

2021-05-12 15:19 UTC, CodingFeles commented on task-3/Calculator-1/Calculator 1/Program.cs
> +                    Console.WriteLine("Вы ввели не допустимый сомвол, попробуйте еще.");
Опечатка

2021-05-12 15:22 UTC, CodingFeles reviewed
Отлично! 
Наличие цикла для обработки множества запросов в одну сессию работы программы - это очень хорошо.
Есть момент: если бы это было приложение для линукса, то было бы абсолютно нормально оставить его с вечным циклом и выходить по системному сигналу (нажимая ctrl+c в консоли, где запущена программа). 
Но это может быть не лучшим подходом для виндоус и возможно, потребуется, отдельная команда выхода из программы. (например, если пользователь вводит "exit", то программа выходит).
Я не уверен, как тут поступить в случае с виндоус, поэтому оставлю решение на Вову.

2021-05-12 15:39 UTC, Tauders requested changes

2021-05-12 15:39 UTC, Tauders commented on task-3/Calculator-1/Calculator 1/Program.cs
> +
Убери лишние пустые строки - обычной одной строки хватает.

2021-05-12 15:39 UTC, Tauders commented on task-3/Calculator-1/Calculator 1/Program.cs
> +namespace Calculator_1
Такой namespace из-за пробела в названии - лучше пробелы в таких местах избегать

2021-05-12 15:39 UTC, Tauders commented on task-3/Calculator-1/Calculator 1/Program.cs
> +
Лучше ограничиться одной пустой строкой

2021-05-12 15:39 UTC, Tauders commented on task-3/Calculator-1/Calculator 1/Program.cs
> +                string action;
Не минус, просто один момент, который может быть в больших функциях не сильно удобен. Переменные можно объявлять в том месте, где они нужны становятся. 
Т.е. `action` сейчас не нужна, но объявлена. В случае, если пользователь введёт некоректное число, она и не понадобится, но зачем-то объявлена.

2021-05-12 15:39 UTC, Tauders commented on task-3/Calculator-1/Calculator 1/Program.cs
> +                    Console.WriteLine("Для продолжения нажмите ENTER");
Можно убрать такое большое количество строк:
```
Console.WriteLine("Для продолжения нажмите ENTER");
```
и оставить их только в конце.

2021-05-12 15:39 UTC, Tauders commented on task-3/Calculator-1/Calculator 1/Program.cs
> +                    Console.WriteLine("Сумма = " + result);
Можно использовать интерполяцию строк

2021-05-12 15:43 UTC, Tauders commented
Всё круто!

Предусмотрены большинство случаев, которые могут возникнуть (некорректный ввод, деление на ноль) через обработку исключений, это очень хороший подход.

Возможность ввода множества раз чисел - хороший шаг.

Лучше добавить возможность выйти из программы через особую команду или сочетание клавиш.

2021-05-12 15:53 UTC, CodingFeles commented on task-3/Calculator-1/Calculator 1/Program.cs
> +namespace Calculator_1
Мне не очень нравятся цифры в названиях типов/нэймспэйсов/проектов. Думаю, что можно просто именовать по сути задания. В репозитории, чуть позже, мы тоже перейдём на нормальное именование проектов, а не task-n.

2021-05-12 15:56 UTC, CodingFeles commented
>или сочетание клавиш.

Так виндоус по умолчанию будет обрабатывать ктрл+ц. Так что оно и так есть :)

> через обработку исключений

Деление на ноль не выбрасывает исключение. Можно, кстати, переделать и заодно обрабатывать исключения по всей логике обработки команд. 
Но думаю, что сейчас это некретично и дальше будут кейсы получше для этого.

**Итого**:

- Из запрашиваемых правок: то, что перечислил Вова по оформлению кода.
- По завершению программы: предлагаю тебе, @RatatataBoom, на выбор: либо оставить как есть, тогда выход из программы будет по ктрл+ц, либо добавить обработку комманды "exit".
- Calculator_1 пока оставить, но в будущем мы уточним правила по именованию и там будет понятнее как именовать проекты, нэймспэйсы и типы.

2021-05-13 14:14 UTC, RatatataBoom commented on task-3/Calculator-1/Calculator 1/Program.cs
> +                    Console.WriteLine("Вы ввели не допустимый сомвол, попробуйте еще.");
Исправлено

2021-05-13 14:15 UTC, Tauders approved these changes

2021-05-13 14:15 UTC, Tauders commented on task-3/Calculator-1/Calculator 1/Program.cs
> +                action = Console.ReadLine();
Можно в одну строку:
```
string action = Console.ReadLine();
```

2021-05-13 14:17 UTC, CodingFeles approved these changes
Всё очень хорошо. Молодец!

2021-05-13 14:17 UTC, merged